// ========================================================
// SOS Hub Canada - Tous les programmes d'immigration canadiens
// Aucune référence au Qatar - 100% Canada
// ========================================================

import type { ImmigrationProgram } from './crm-types';

export const PROGRAM_CATEGORIES: Record<string, string> = {
  express_entry: 'Entrée express',
  pnp: 'Programmes provinciaux',
  family: 'Parrainage familial',
  temporaire: 'Résidence temporaire',
  refugie: 'Réfugiés et asile',
  citoyennete: 'Citoyenneté',
  residence_permanente: 'Résidence permanente',
  humanitaire: 'Humanitaire',
  caregiver: 'Aides familiaux',
  pilot: 'Programmes pilotes',
  affaires: 'Immigration d\'affaires',
};

export const IMMIGRATION_PROGRAMS: ImmigrationProgram[] = [
  // ============ ENTRÉE EXPRESS ============
  {
    id: 'ee-fsw', category: 'express_entry',
    name: 'Entrée express - Travailleurs qualifiés (fédéral)',
    description: 'Programme pour les travailleurs qualifiés avec expérience de travail étranger',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476', 'imm5562'],
    processingTime: '6 mois',
    fees: { government: 1365, service: 3500 },
    requirements: ['67 points grille FSW', 'CLB 7 minimum', '1 an expérience qualifiée NOC TEER 0/1/2/3'],
  },
  {
    id: 'ee-cec', category: 'express_entry',
    name: 'Entrée express - Catégorie de l\'expérience canadienne (CEC)',
    description: 'Pour ceux ayant de l\'expérience de travail canadienne qualifiée',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '6 mois',
    fees: { government: 1365, service: 3000 },
    requirements: ['1 an expérience canadienne qualifiée', 'CLB 7 (TEER 0/1) ou CLB 5 (TEER 2/3)'],
  },
  {
    id: 'ee-fst', category: 'express_entry',
    name: 'Entrée express - Travailleurs de métiers spécialisés (TFMS)',
    description: 'Programme pour les gens de métier qualifiés',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '6 mois',
    fees: { government: 1365, service: 3000 },
    requirements: ['2 ans expérience métier spécialisé', 'Offre emploi ou certificat qualification provincial', 'CLB 5 oral, CLB 4 écrit'],
  },
  // ============ PROGRAMMES PROVINCIAUX ============
  {
    id: 'pnp-quebec-pstq', category: 'pnp',
    name: 'Programme de sélection des travailleurs qualifiés du Québec (PSTQ/Arrima)',
    description: 'Programme de sélection permanente du Québec via le portail Arrima',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 4000 },
    requirements: ['Invitation Arrima', 'CSQ obtenu', 'Demande RP fédérale ensuite'],
  },
  {
    id: 'pnp-peq', category: 'pnp',
    name: 'Programme de l\'expérience québécoise (PEQ)',
    description: 'Voie accélérée pour travailleurs temporaires et diplômés au Québec',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5476'],
    processingTime: '12-16 mois',
    fees: { government: 1365, service: 3500 },
    requirements: ['Travail ou diplôme au Québec', 'Français oral B2 (NCLC 7)', 'Attestation valeurs démocratiques'],
  },
  {
    id: 'pnp-ontario', category: 'pnp',
    name: 'Programme des candidats de l\'Ontario (OINP)',
    description: 'Programme de nomination provinciale de l\'Ontario',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 4000 },
    requirements: ['Nomination provinciale Ontario', 'Varie selon le volet choisi'],
  },
  {
    id: 'pnp-cb', category: 'pnp',
    name: 'Programme des candidats de la Colombie-Britannique (BC PNP)',
    description: 'Programme de nomination de la Colombie-Britannique',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 4000 },
    requirements: ['Nomination provinciale C.-B.', 'Varie selon le volet choisi'],
  },
  {
    id: 'pnp-alberta', category: 'pnp',
    name: 'Programme d\'immigration de l\'Alberta (AAIP)',
    description: 'Programme de nomination de l\'Alberta',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 4000 },
    requirements: ['Nomination provinciale Alberta', 'Varie selon le volet choisi'],
  },
  {
    id: 'pnp-manitoba', category: 'pnp',
    name: 'Programme des candidats du Manitoba (MPNP)',
    description: 'Programme de nomination du Manitoba',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 3500 },
    requirements: ['Nomination provinciale Manitoba', 'Lien avec le Manitoba'],
  },
  {
    id: 'pnp-saskatchewan', category: 'pnp',
    name: 'Programme des candidats de la Saskatchewan (SINP)',
    description: 'Programme de nomination de la Saskatchewan',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 3500 },
    requirements: ['Nomination provinciale Saskatchewan'],
  },
  {
    id: 'pnp-nb', category: 'pnp',
    name: 'Programme des candidats du Nouveau-Brunswick',
    description: 'Programme de nomination du Nouveau-Brunswick',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 3500 },
    requirements: ['Nomination provinciale N.-B.'],
  },
  {
    id: 'pnp-ne', category: 'pnp',
    name: 'Programme des candidats de la Nouvelle-Écosse (NSNP)',
    description: 'Programme de nomination de la Nouvelle-Écosse',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 3500 },
    requirements: ['Nomination provinciale N.-É.'],
  },
  // ============ PARRAINAGE FAMILIAL ============
  {
    id: 'family-spouse', category: 'family',
    name: 'Parrainage - Époux / Conjoint de fait',
    description: 'Parrainer votre époux(se) ou conjoint(e) de fait pour la résidence permanente',
    requiredForms: ['imm1344', 'imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476', 'imm5532', 'imm5409', 'imm5540'],
    processingTime: '12 mois',
    fees: { government: 1625, service: 4000 },
    requirements: ['Être citoyen canadien ou RP', 'Prouver relation authentique', '18 ans minimum'],
  },
  {
    id: 'family-parents', category: 'family',
    name: 'Parrainage - Parents et grands-parents (PGP)',
    description: 'Parrainer vos parents et grands-parents',
    requiredForms: ['imm1344', 'imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476', 'imm5768'],
    processingTime: '20-24 mois',
    fees: { government: 1625, service: 4500 },
    requirements: ['Citoyen canadien ou RP', 'Revenu minimum (SFR+30%)', 'Engagement financier 20 ans'],
  },
  {
    id: 'family-child', category: 'family',
    name: 'Parrainage - Enfant à charge',
    description: 'Parrainer un enfant à charge',
    requiredForms: ['imm1344', 'imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5476'],
    processingTime: '12 mois',
    fees: { government: 1625, service: 3000 },
    requirements: ['Citoyen canadien ou RP', 'Enfant de moins de 22 ans non marié'],
  },
  {
    id: 'family-other', category: 'family',
    name: 'Parrainage - Autre membre de la famille',
    description: 'Parrainer un frère, une sœur, un neveu, une nièce ou un petit-enfant orphelin',
    requiredForms: ['imm1344', 'imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5476'],
    processingTime: '24 mois',
    fees: { government: 1625, service: 3500 },
    requirements: ['Aucun autre parent parrainable', 'Membre de la famille admissible'],
  },
  // ============ RÉSIDENCE TEMPORAIRE ============
  {
    id: 'study-permit', category: 'temporaire',
    name: 'Permis d\'études',
    description: 'Étudier dans un établissement d\'enseignement désigné (EED) au Canada',
    requiredForms: ['imm1294', 'imm5645', 'imm5476', 'imm0008-schedule1'],
    processingTime: '4-16 semaines',
    fees: { government: 150, service: 1500 },
    requirements: ['Lettre d\'acceptation d\'un EED', 'Preuve de capacité financière', 'Examen médical si requis'],
  },
  {
    id: 'study-extension', category: 'temporaire',
    name: 'Prolongation de permis d\'études',
    description: 'Prolonger votre permis d\'études',
    requiredForms: ['imm5709', 'imm5645', 'imm5476'],
    processingTime: '4-12 semaines',
    fees: { government: 150, service: 800 },
    requirements: ['Permis d\'études valide ou statut implicite', 'Lettre d\'acceptation', 'Fonds suffisants'],
  },
  {
    id: 'work-permit-lmia', category: 'temporaire',
    name: 'Permis de travail fermé (avec EIMT)',
    description: 'Permis de travail basé sur une Étude d\'impact sur le marché du travail approuvée',
    requiredForms: ['imm1295', 'imm5645', 'imm5476', 'imm0008-schedule1'],
    processingTime: '4-16 semaines',
    fees: { government: 155, service: 2000 },
    requirements: ['EIMT positive', 'Offre d\'emploi valide', 'Qualifications pour le poste'],
  },
  {
    id: 'work-permit-open', category: 'temporaire',
    name: 'Permis de travail ouvert',
    description: 'Permis de travail sans employeur spécifique (conjoint, PTPD, vulnérable, etc.)',
    requiredForms: ['imm1295', 'imm5645', 'imm5476'],
    processingTime: '4-12 semaines',
    fees: { government: 255, service: 1500 },
    requirements: ['Admissibilité selon catégorie spécifique'],
  },
  {
    id: 'pgwp', category: 'temporaire',
    name: 'Permis de travail post-diplôme (PTPD)',
    description: 'Travailler au Canada après l\'obtention d\'un diplôme d\'un EED',
    requiredForms: ['imm1295', 'imm5645', 'imm5476'],
    processingTime: '4-12 semaines',
    fees: { government: 255, service: 1000 },
    requirements: ['Diplôme d\'un EED éligible', 'Demande dans les 180 jours', 'Permis d\'études valide'],
  },
  {
    id: 'trv-visitor', category: 'temporaire',
    name: 'Visa de résident temporaire (VRT) - Visiteur',
    description: 'Visiter le Canada pour tourisme, famille ou affaires',
    requiredForms: ['imm5257', 'imm5645', 'imm5476', 'imm5257b'],
    processingTime: '2-12 semaines',
    fees: { government: 100, service: 800 },
    requirements: ['Passeport valide', 'Preuve de fonds', 'Liens avec pays d\'origine', 'But légitime de visite'],
  },
  {
    id: 'super-visa', category: 'temporaire',
    name: 'Super visa (parents et grands-parents)',
    description: 'Visa multi-entrées pour parents/grands-parents, séjours jusqu\'à 5 ans',
    requiredForms: ['imm5257', 'imm5645', 'imm5476', 'imm5484'],
    processingTime: '4-16 semaines',
    fees: { government: 100, service: 1200 },
    requirements: ['Enfant/petit-enfant citoyen ou RP', 'Assurance médicale 100 000$', 'Lettre d\'invitation', 'Revenu minimum SFR'],
  },
  {
    id: 'eta', category: 'temporaire',
    name: 'Autorisation de voyage électronique (AVE)',
    description: 'Autorisation pour voyager par avion au Canada (pays exemptés de visa)',
    requiredForms: [],
    processingTime: 'Quelques minutes',
    fees: { government: 7, service: 200 },
    requirements: ['Passeport valide', 'Pays exempté de visa'],
  },
  {
    id: 'mobilite-francophone', category: 'temporaire',
    name: 'Mobilité francophone',
    description: 'Permis de travail sans EIMT pour travailleurs francophones hors Québec',
    requiredForms: ['imm1295', 'imm5645', 'imm5476'],
    processingTime: '4-8 semaines',
    fees: { government: 155, service: 1500 },
    requirements: ['Francophone', 'Offre d\'emploi hors Québec', 'NOC TEER 0/1/2/3'],
  },
  {
    id: 'trp', category: 'temporaire',
    name: 'Permis de séjour temporaire (PST)',
    description: 'Pour personnes interdites de territoire ayant des raisons impérieuses d\'entrer au Canada',
    requiredForms: ['imm1444', 'imm5645', 'imm5476'],
    processingTime: '2-6 mois',
    fees: { government: 200, service: 2500 },
    requirements: ['Motifs impérieux', 'Interdiction de territoire documentée'],
  },
  {
    id: 'restoration', category: 'temporaire',
    name: 'Rétablissement de statut',
    description: 'Rétablir un statut temporaire expiré (moins de 90 jours)',
    requiredForms: ['imm5709', 'imm5645', 'imm5476'],
    processingTime: '4-12 semaines',
    fees: { government: 379, service: 1000 },
    requirements: ['Demande dans les 90 jours après expiration', 'Conditions du statut initial respectées'],
  },
  // ============ RÉFUGIÉS ET ASILE ============
  {
    id: 'asile-inland', category: 'refugie',
    name: 'Demande d\'asile au Canada (intérieur)',
    description: 'Demande de protection pour les personnes déjà au Canada craignant persécution',
    requiredForms: ['boc-form', 'imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5476', 'imm5611'],
    processingTime: '12-24 mois',
    fees: { government: 0, service: 5000 },
    requirements: ['Être au Canada', 'Crainte fondée de persécution', 'Formulaire FDA dans les 15 jours'],
  },
  {
    id: 'asile-poe', category: 'refugie',
    name: 'Demande d\'asile au point d\'entrée',
    description: 'Demande de protection à l\'arrivée au Canada (aéroport, frontière)',
    requiredForms: ['boc-form', 'imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5476'],
    processingTime: '12-24 mois',
    fees: { government: 0, service: 5000 },
    requirements: ['Arriver à un point d\'entrée officiel', 'Crainte de persécution', 'Pas d\'exclusion ETPS'],
  },
  {
    id: 'refugee-rap', category: 'refugie',
    name: 'Réfugiés pris en charge par le gouvernement (RPG/PAR)',
    description: 'Programme d\'aide à la réinstallation pour réfugiés référés par le HCR',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5476'],
    processingTime: '12-36 mois',
    fees: { government: 0, service: 0 },
    requirements: ['Référé par le HCR ou un État', 'Hors du pays de nationalité'],
  },
  {
    id: 'refugee-psr', category: 'refugie',
    name: 'Parrainage privé de réfugiés (PPR)',
    description: 'Réfugiés parrainés par des groupes privés ou des SAH',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5476', 'imm5373'],
    processingTime: '18-36 mois',
    fees: { government: 0, service: 3000 },
    requirements: ['Groupe de parrainage constitué (G5 ou SAH)', 'Plan d\'établissement', 'Capacité financière 12 mois'],
  },
  {
    id: 'protected-person-pr', category: 'refugie',
    name: 'Résidence permanente - Personne protégée',
    description: 'Demande de RP après avoir obtenu le statut de personne protégée au Canada',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476', 'imm5562'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 3000 },
    requirements: ['Statut de personne protégée', 'Pas d\'interdiction de territoire', 'Examen médical à jour'],
  },
  {
    id: 'prra', category: 'refugie',
    name: 'Examen des risques avant renvoi (ERAR)',
    description: 'Évaluation des risques pour personnes faisant l\'objet d\'une mesure de renvoi',
    requiredForms: ['imm0008', 'imm5669', 'imm5476'],
    processingTime: '6-12 mois',
    fees: { government: 0, service: 3500 },
    requirements: ['Mesure de renvoi exécutoire', 'Invitation ERAR reçue', 'Nouveaux éléments de preuve'],
  },
  // ============ CITOYENNETÉ ============
  {
    id: 'citizenship-adult', category: 'citoyennete',
    name: 'Citoyenneté canadienne - Adulte (18+)',
    description: 'Devenir citoyen canadien',
    requiredForms: ['cit0002', 'cit0007', 'imm5476'],
    processingTime: '12 mois',
    fees: { government: 630, service: 1500 },
    requirements: ['Statut de RP', '1095 jours de présence physique en 5 ans', 'Déclarations de revenus 3 ans', 'Test de connaissances et langue'],
  },
  {
    id: 'citizenship-minor', category: 'citoyennete',
    name: 'Citoyenneté canadienne - Mineur',
    description: 'Demande de citoyenneté pour enfant de moins de 18 ans',
    requiredForms: ['cit0003', 'imm5476'],
    processingTime: '12 mois',
    fees: { government: 100, service: 800 },
    requirements: ['Statut de RP', 'Parent citoyen canadien ou demande conjointe parent'],
  },
  // ============ RÉSIDENCE PERMANENTE ============
  {
    id: 'pr-card-renewal', category: 'residence_permanente',
    name: 'Renouvellement de la carte de résident permanent',
    description: 'Renouveler votre carte RP expirée ou sur le point d\'expirer',
    requiredForms: ['imm5444', 'imm5476'],
    processingTime: '2-6 mois',
    fees: { government: 50, service: 500 },
    requirements: ['Statut de RP valide', '730 jours de présence physique en 5 ans'],
  },
  // ============ HUMANITAIRE ============
  {
    id: 'humanitarian', category: 'humanitaire',
    name: 'Considérations d\'ordre humanitaire (CH)',
    description: 'Demande de RP basée sur des motifs humanitaires exceptionnels',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476', 'imm5562'],
    processingTime: '24-48 mois',
    fees: { government: 1365, service: 5000 },
    requirements: ['Circonstances humanitaires exceptionnelles', 'Établissement significatif au Canada', 'Intérêt supérieur de l\'enfant si applicable'],
  },
  {
    id: 'criminal-rehab', category: 'humanitaire',
    name: 'Réhabilitation criminelle',
    description: 'Surmonter l\'interdiction de territoire pour criminalité',
    requiredForms: ['imm1444', 'imm5645', 'imm5476'],
    processingTime: '6-12 mois',
    fees: { government: 1000, service: 3000 },
    requirements: ['5 ans écoulés depuis fin de la peine', 'Preuve de réhabilitation'],
  },
  // ============ AIDES FAMILIAUX ============
  {
    id: 'caregiver-children', category: 'caregiver',
    name: 'Gardiens d\'enfants en milieu familial',
    description: 'RP pour gardiens d\'enfants en milieu familial',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 3000 },
    requirements: ['Expérience de travail qualifiée au Canada', 'CLB 5', 'Études postsecondaires'],
  },
  {
    id: 'caregiver-medical', category: 'caregiver',
    name: 'Aides-soignants à domicile',
    description: 'RP pour aides-soignants à domicile',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 3000 },
    requirements: ['Expérience de travail qualifiée au Canada', 'CLB 5', 'Études postsecondaires'],
  },
  // ============ PROGRAMMES PILOTES ============
  {
    id: 'atlantic-immigration', category: 'pilot',
    name: 'Programme d\'immigration atlantique (PIA)',
    description: 'RP pour travailler dans les provinces atlantiques (N.-B., N.-É., Î.-P.-É., T.-N.-L.)',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12 mois',
    fees: { government: 1365, service: 3500 },
    requirements: ['Offre d\'emploi d\'un employeur désigné', 'Plan d\'établissement', 'CLB 4-5 selon le niveau'],
  },
  {
    id: 'rural-northern', category: 'pilot',
    name: 'Immigration dans les communautés rurales et du Nord',
    description: 'Immigration vers les communautés rurales et nordiques participantes',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 3500 },
    requirements: ['Recommandation communautaire', 'Offre d\'emploi admissible', 'CLB 4-6'],
  },
  {
    id: 'agri-food', category: 'pilot',
    name: 'Programme pilote sur l\'agroalimentaire',
    description: 'RP pour travailleurs du secteur agroalimentaire',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-18 mois',
    fees: { government: 1365, service: 3000 },
    requirements: ['1 an expérience agroalimentaire au Canada', 'EIMT', 'CLB 4', 'Secondaire complété'],
  },
  // ============ IMMIGRATION D'AFFAIRES ============
  {
    id: 'startup-visa', category: 'affaires',
    name: 'Visa pour démarrage d\'entreprise (Start-up Visa)',
    description: 'RP pour entrepreneurs innovants avec appui d\'une organisation désignée',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '12-16 mois',
    fees: { government: 2140, service: 5000 },
    requirements: ['Lettre d\'appui d\'une organisation désignée', 'CLB 5', 'Fonds d\'établissement suffisants'],
  },
  {
    id: 'self-employed', category: 'affaires',
    name: 'Travailleurs autonomes (culture/sport)',
    description: 'RP pour personnes ayant des activités culturelles, artistiques ou sportives',
    requiredForms: ['imm0008', 'imm0008-schedule1', 'imm5669', 'imm5645', 'imm5406', 'imm5476'],
    processingTime: '24-36 mois',
    fees: { government: 1625, service: 4000 },
    requirements: ['2 ans d\'expérience pertinente', 'Capacité de contribution significative au Canada'],
  },
  {
    id: 'intra-company', category: 'affaires',
    name: 'Transfert intra-société',
    description: 'Permis de travail pour cadres, gestionnaires ou employés spécialisés transférés',
    requiredForms: ['imm1295', 'imm5645', 'imm5476'],
    processingTime: '4-12 semaines',
    fees: { government: 155, service: 2500 },
    requirements: ['Emploi continu chez l\'employeur étranger', 'Poste de cadre, gestionnaire ou connaissances spécialisées', 'Lien entre les entreprises'],
  },
];
