import {
  TrendingUp, Award, Briefcase, GraduationCap, Heart,
  Plane, Building2, Globe2,
} from 'lucide-react';

export const services = [
  {
    id: 'entree-express',
    icon: TrendingUp,
    title: 'Entrée Express',
    subtitle: 'Résidence permanente fédérale',
    color: 'from-blue-500 to-blue-700',
    image: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=800&h=400&fit=crop',
    desc: 'Le programme Entrée Express est la voie la plus rapide vers la résidence permanente au Canada pour les travailleurs qualifiés.',
    includes: [
      'Évaluation du profil et calcul CRS',
      'Création du profil Entrée Express',
      'Préparation de la demande de RP',
      'Suivi des tirages et optimisation du score',
      'Assistance pour l\'ECA et les tests de langue',
    ],
    programs: ['Travailleurs qualifiés fédéraux (FSW)', 'Classe de l\'expérience canadienne (CEC)', 'Métiers spécialisés fédéraux (FST)'],
    timeline: '6-12 mois',
  },
  {
    id: 'peq',
    icon: Award,
    title: 'Programmes du Québec',
    subtitle: 'PEQ, PRTQ, Arrima',
    color: 'from-emerald-500 to-emerald-700',
    image: 'https://images.unsplash.com/photo-1519178614-68673b201f36?w=800&h=400&fit=crop',
    desc: 'Programmes d\'immigration spécifiques au Québec, offrant des voies privilégiées pour les francophones et les diplômés québécois.',
    includes: [
      'PEQ: diplômés et travailleurs temporaires',
      'PRTQ via le portail Arrima',
      'Demande de CSQ (Certificat de sélection)',
      'Transition du CSQ vers la RP fédérale',
      'Accompagnement francisation si nécessaire',
    ],
    programs: ['PEQ Diplômés', 'PEQ Travailleurs', 'PRTQ / Arrima', 'PTQF'],
    timeline: '6-18 mois',
  },
  {
    id: 'permis-travail',
    icon: Briefcase,
    title: 'Permis de travail',
    subtitle: 'Ouvert et fermé',
    color: 'from-purple-500 to-purple-700',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=400&fit=crop',
    desc: 'Obtenez votre permis de travail au Canada, que ce soit pour un employeur spécifique ou un permis ouvert.',
    includes: [
      'EIMT/LMIA pour l\'employeur',
      'Permis fermé (employeur spécifique)',
      'Permis ouvert (PTMO, conjoint)',
      'Mobilité francophone',
      'PGWP (Permis post-diplôme)',
    ],
    programs: ['EIMT/LMIA', 'Mobilité francophone', 'Jeunes professionnels (EIC)', 'PGWP'],
    timeline: '2-6 mois',
  },
  {
    id: 'permis-etudes',
    icon: GraduationCap,
    title: 'Permis d\'études',
    subtitle: 'Étudier au Canada',
    color: 'from-amber-500 to-amber-700',
    image: 'https://images.unsplash.com/photo-1627556704302-624286467c65?w=800&h=400&fit=crop',
    desc: 'Étudiez au Canada et ouvrez la porte à l\'immigration permanente grâce à un diplôme canadien.',
    includes: [
      'Choix du programme et de l\'établissement',
      'CAQ (Certificat d\'acceptation du Québec)',
      'Demande de permis d\'études',
      'Permis de travail étudiant (20h/sem)',
      'Planification post-diplôme (PGWP → RP)',
    ],
    programs: ['CAQ + Permis d\'études', 'Co-op/Stage', 'Programme court', 'Cycles supérieurs'],
    timeline: '3-6 mois',
  },
  {
    id: 'parrainage',
    icon: Heart,
    title: 'Parrainage familial',
    subtitle: 'Réunification familiale',
    color: 'from-rose-500 to-rose-700',
    image: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=800&h=400&fit=crop',
    desc: 'Réunissez votre famille au Canada en parrainant votre conjoint, vos parents ou vos enfants.',
    includes: [
      'Parrainage de conjoint/conjointe',
      'Parrainage de parents et grands-parents',
      'Super visa pour parents',
      'Parrainage d\'enfants à charge',
      'Accompagnement complet du processus',
    ],
    programs: ['Conjoint/Partenaire', 'Parents et grands-parents', 'Enfants à charge', 'Super Visa'],
    timeline: '6-24 mois',
  },
  {
    id: 'relocalisation',
    icon: Plane,
    title: 'Relocalisation et intégration',
    subtitle: 'Service clé en main',
    color: 'from-cyan-500 to-cyan-700',
    image: 'https://images.unsplash.com/photo-1519832979-6fa011b87667?w=800&h=400&fit=crop',
    desc: 'Un accompagnement complet pour votre installation au Canada: logement, emploi, démarches administratives et intégration.',
    includes: [
      'Recherche de logement',
      'Ouverture de compte bancaire',
      'Inscription scolaire des enfants',
      'Obtention du NAS et RAMQ',
      'Orientation professionnelle et réseautage',
    ],
    programs: ['Package Arrivée', 'Intégration professionnelle', 'Installation familiale', 'Accompagnement continu'],
    timeline: '1-3 mois',
  },
  {
    id: 'employeurs',
    icon: Building2,
    title: 'Services aux employeurs',
    subtitle: 'Accompagnement des employeurs',
    color: 'from-indigo-500 to-indigo-700',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=400&fit=crop',
    desc: 'Nous aidons les employeurs canadiens à recruter des travailleurs étrangers qualifiés en toute conformité.',
    includes: [
      'Demande d\'EIMT/LMIA',
      'Conformité au programme TET',
      'Accompagnement à l\'embauche de travailleurs étrangers',
      'Gestion des permis de travail',
      'Accompagnement en intégration des employés',
    ],
    programs: ['EIMT volet hauts salaires', 'EIMT volet bas salaires', 'PTET', 'Mobilité internationale'],
    timeline: '3-6 mois',
  },
  {
    id: 'visa',
    icon: Globe2,
    title: 'Visa et résidence temporaire',
    subtitle: 'Visiter le Canada',
    color: 'from-teal-500 to-teal-700',
    image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&h=400&fit=crop',
    desc: 'Obtenez votre visa de résident temporaire, super visa, ou autorisation de voyage électronique (AVE/eTA).',
    includes: [
      'Visa de résident temporaire (VRT)',
      'Super Visa (parents/grands-parents)',
      'AVE / eTA',
      'Prolongation de séjour',
      'Restauration de statut',
    ],
    programs: ['VRT', 'Super Visa', 'AVE/eTA', 'Prolongation'],
    timeline: '2-8 semaines',
  },
];
