"use client";
import { crmFetch } from '@/lib/crm-fetch';
import { useState, useMemo, useEffect } from "react";
import { useCrm, getUserName, DEMO_USERS } from "@/lib/crm-store";
import {
  CASE_STATUS_LABELS, CASE_STATUS_COLORS, PRIORITY_LABELS, PRIORITY_COLORS,
  ROLE_PERMISSIONS, FORM_STATUS_LABELS,
} from "@/lib/crm-types";
import type { Case, CaseForm, CaseStatus, TimelineEvent, Client } from "@/lib/crm-types";
import { IMMIGRATION_PROGRAMS, PROGRAM_CATEGORIES } from "@/lib/crm-programs";
import { generateContractFromCase, findPricingTierByProgram, FRAIS_OUVERTURE_DOSSIER } from "@/lib/crm-pricing-2026";
import {
  calculateCRS, calculateMIFI, getCrsImprovementAdvice, getMifiImprovementAdvice,
  getDefaultProfile, CRS_RECENT_CUTOFFS, MIFI_THRESHOLD_ESTIMATE,
  type ScoringProfile, type CrsBreakdown, type MifiBreakdown, type ImprovementAdvice, type EducationLevel,
} from "@/lib/crm-scoring";
import Link from "next/link";
import {
  FolderOpen, Plus, Search, Eye, X, Filter, LayoutGrid, List, Clock, AlertTriangle,
  FileSignature, DollarSign, CheckCircle2, Calculator, TrendingUp, Send, Mail,
  Lightbulb, Target, ArrowRight, CheckCircle, ListChecks, Square, CheckSquare, MessageSquare,
  Edit3, Trash2, ChevronDown, ChevronRight, UserCircle, Zap, Info, RotateCcw,
} from "lucide-react";
import NotesSection, { DOSSIER_NOTE_CATEGORIES } from "@/components/NotesSection";
import { generateTasksForProgram, getTaskConfigForProgram, PHASE_CONFIG } from "@/lib/crm-task-templates";

// --- Task management types ---
type TaskStatus = 'a_faire' | 'en_cours' | 'terminee';
type TaskPriority = 'haute' | 'moyenne' | 'basse';

interface CaseTask {
  id: string;
  caseId: string;
  title: string;
  assignee: string;
  dueDate: string;
  priority: TaskPriority;
  status: TaskStatus;
  createdAt: string;
  phase?: string;
  description?: string;
  autoGenerated?: boolean;
}

const TASK_STATUS_LABELS: Record<TaskStatus, string> = {
  a_faire: 'A faire',
  en_cours: 'En cours',
  terminee: 'Terminee',
};

const TASK_PRIORITY_COLORS: Record<TaskPriority, string> = {
  haute: 'bg-red-100 text-red-700',
  moyenne: 'bg-orange-100 text-orange-700',
  basse: 'bg-gray-100 text-gray-500',
};

const TASKS_KEY = 'soshub_case_tasks';

function loadTasks(): CaseTask[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem(TASKS_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch (err) { console.error('Erreur chargement taches:', err); return []; }
}

function saveTasks(tasks: CaseTask[]): void {
  if (typeof window !== 'undefined') {
    localStorage.setItem(TASKS_KEY, JSON.stringify(tasks));
  }
}

function getTaskCountForCase(caseId: string, tasks: CaseTask[]): number {
  return tasks.filter(t => t.caseId === caseId && t.status !== 'terminee').length;
}

// --- Programmes éligibles au scoring automatique ---
const EE_PROGRAMS = ['ee-fsw', 'ee-cec', 'ee-fst'];
const PSTQ_PROGRAMS = ['pnp-quebec-pstq', 'pnp-peq'];
const SCORING_PROGRAMS = [...EE_PROGRAMS, ...PSTQ_PROGRAMS];

function isScoringProgram(programId: string): 'crs' | 'mifi' | null {
  if (EE_PROGRAMS.includes(programId)) return 'crs';
  if (PSTQ_PROGRAMS.includes(programId)) return 'mifi';
  return null;
}

// --- Construire un profil de scoring à partir du client ---
function buildProfileFromClient(client: Client): ScoringProfile {
  const p = getDefaultProfile();

  // Âge
  if (client.dateOfBirth) {
    const birth = new Date(client.dateOfBirth);
    const today = new Date();
    p.age = Math.floor((today.getTime() - birth.getTime()) / 31557600000);
  }

  // Situation maritale
  if (['Marié', 'Mariée', 'Conjoint de fait'].includes(client.maritalStatus)) {
    p.maritalStatus = 'married_common_law';
    p.spouseAccompanying = client.familyMembers.some(fm =>
      ['Époux', 'Épouse', 'Conjoint', 'Conjointe'].includes(fm.relationship) && fm.accompany
    );
  }

  // Éducation
  const eduLower = client.education.toLowerCase();
  if (eduLower.includes('doctorat') || eduLower.includes('phd')) p.educationLevel = 'doctoral';
  else if (eduLower.includes('maîtrise') || eduLower.includes('master') || eduLower.includes('mba')) p.educationLevel = 'masters';
  else if (eduLower.includes('baccalauréat') || eduLower.includes('bachelor')) p.educationLevel = 'bachelors';
  else if (eduLower.includes('dec') || eduLower.includes('2 ans')) p.educationLevel = 'two_year_post_secondary';
  else if (eduLower.includes('dep') || eduLower.includes('aec') || eduLower.includes('1 an')) p.educationLevel = 'one_year_post_secondary';

  // Langues
  function parseCLB(str: string): number {
    const m = str.match(/(\d+)/);
    return m ? parseInt(m[1]) : 5;
  }
  if (client.languageFrench) {
    const nclc = parseCLB(client.languageFrench);
    p.firstLanguage = 'french';
    p.firstLanguageScores = { speaking: nclc, listening: nclc, reading: nclc, writing: nclc };
  }
  if (client.languageEnglish) {
    const clb = parseCLB(client.languageEnglish);
    if (p.firstLanguage === 'french') {
      p.secondLanguageScores = { speaking: clb, listening: clb, reading: clb, writing: clb };
    } else {
      p.firstLanguage = 'english';
      p.firstLanguageScores = { speaking: clb, listening: clb, reading: clb, writing: clb };
    }
  }

  // Expérience
  const expMatch = client.workExperience.match(/(\d+)\s*ans?/i);
  if (expMatch) {
    const years = parseInt(expMatch[1]);
    if (client.currentCountry === 'Canada') {
      p.canadianWorkExperienceYears = years;
    } else {
      p.foreignWorkExperienceYears = years;
    }
  }

  // Québec-specific
  p.enfants = client.dependants;
  if (client.province === 'QC' || client.currentCountry === 'Canada') {
    p.sejourQuebec = true;
  }
  p.capaciteFinanciere = true;

  return p;
}

// --- Générer le contenu HTML du courriel avec résultats d'admissibilité ---
function generateScoringEmail(
  client: Client,
  scoringType: 'crs' | 'mifi',
  score: number,
  threshold: number,
  advice: ImprovementAdvice[],
  programName: string,
): { subject: string; body: string } {
  const above = score >= threshold;
  const topAdvice = advice.filter(a => a.actionable).slice(0, 4);
  const fullName = `${client.firstName} ${client.lastName}`.trim();

  const subject = scoringType === 'crs'
    ? `${client.firstName}, vos résultats CRS sont prêts (${score} pts) — SOS Hub Canada`
    : `${client.firstName}, vos résultats MIFI sont prêts (${score} pts) — SOS Hub Canada`;

  const systemLabel = scoringType === 'crs' ? 'CRS (Entrée express)' : 'MIFI (PSTQ/Arrima)';
  const thresholdLabel = scoringType === 'crs' ? 'Seuil derniers tirages' : 'Seuil estimé Arrima';
  const statusColor = above ? '#059669' : '#D97706';
  const statusText = above ? 'QUALIFIÉ — Profil compétitif' : `${threshold - score} points sous le seuil`;
  const statusBg = above ? '#F0FDF4' : '#FEF3C7';

  const adviceHtml = topAdvice.map((a, i) => `
    <tr>
      <td style="padding:10px;vertical-align:top;width:28px">
        <div style="width:24px;height:24px;background:#D4A03C;border-radius:50%;text-align:center;line-height:24px;color:#FFF;font-size:12px;font-weight:800">${i + 1}</div>
      </td>
      <td style="padding:10px;vertical-align:top">
        <div style="font-size:13px;font-weight:700;color:#1B2559">${a.category} <span style="color:#9CA3AF;font-weight:400">(${a.currentPoints}/${a.maxPoints} pts)</span></div>
        <div style="font-size:12px;color:#4B5563;margin-top:2px">${a.advice}</div>
      </td>
    </tr>`).join('');

  const body = `<!DOCTYPE html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F3F4F6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif">
<div style="max-width:600px;margin:0 auto;background:#FFFFFF">

<!-- HEADER -->
<div style="background-color:#1B2559;padding:32px 24px;text-align:center">
  <div style="font-size:28px;font-weight:900;color:#FFFFFF;letter-spacing:-1px">[ SOS <span style="color:#D4A03C">HUB</span> ]</div>
  <div style="color:#D4A03C;font-size:11px;font-weight:700;letter-spacing:4px;margin-top:4px">RELOCALISATION & SERVICES</div>
</div>

<!-- URGENCY BAR -->
<div style="background-color:#D4A03C;padding:12px 24px;text-align:center">
  <span style="color:#FFFFFF;font-size:13px;font-weight:700">VOS RÉSULTATS D'ANALYSE ${systemLabel.toUpperCase()} SONT PRÊTS</span>
</div>

<!-- GREETING -->
<div style="padding:32px 24px 16px">
  <h1 style="color:#1B2559;font-size:22px;margin:0 0 12px">Bonjour ${client.firstName},</h1>
  <p style="color:#4B5563;font-size:14px;line-height:1.6;margin:0">
    Suite à l'analyse de votre dossier pour le programme <strong style="color:#1B2559">« ${programName} »</strong>,
    voici les résultats de votre évaluation. ${above
      ? '<strong style="color:#059669">Bonne nouvelle — votre profil est compétitif !</strong>'
      : 'Votre profil présente du potentiel avec quelques améliorations recommandées.'}
  </p>
</div>

<!-- ═══ SCORE PRINCIPAL ═══ -->
<div style="margin:0 24px;background:${statusBg};border-radius:12px;padding:24px;border:2px solid ${statusColor};text-align:center">
  <div style="font-size:11px;color:${statusColor};font-weight:700;text-transform:uppercase;letter-spacing:2px;margin-bottom:8px">${systemLabel}</div>
  <div style="font-size:48px;font-weight:900;color:#1B2559;line-height:1">${score}</div>
  <div style="font-size:12px;color:#6B7280;margin-top:4px">sur ${scoringType === 'crs' ? '1 200' : '1 320'} points</div>
  <div style="margin:12px auto;width:80%;height:8px;background:#E5E7EB;border-radius:4px;overflow:hidden">
    <div style="width:${Math.min(100, (score / threshold) * 100)}%;height:100%;background:${statusColor};border-radius:4px"></div>
  </div>
  <table style="width:100%;border-collapse:collapse;margin-top:8px">
    <tr>
      <td style="text-align:center;padding:4px">
        <div style="font-size:11px;color:#6B7280">${thresholdLabel}</div>
        <div style="font-size:16px;font-weight:800;color:#1B2559">${threshold} pts</div>
      </td>
      <td style="text-align:center;padding:4px;border-left:1px solid ${statusColor}40">
        <div style="font-size:11px;color:#6B7280">Statut</div>
        <div style="font-size:12px;font-weight:800;color:${statusColor}">${statusText}</div>
      </td>
    </tr>
  </table>
</div>

${topAdvice.length > 0 ? `
<!-- ═══ RECOMMANDATIONS ═══ -->
<div style="margin:24px">
  <div style="font-size:12px;color:#1B2559;font-weight:800;text-transform:uppercase;letter-spacing:1px;margin-bottom:10px;padding-bottom:6px;border-bottom:2px solid #D4A03C">
    Recommandations pour améliorer votre score
  </div>
  <table style="width:100%;border-collapse:collapse">${adviceHtml}</table>
</div>` : ''}

<!-- ═══ CE QUE SOS HUB PEUT FAIRE ═══ -->
<div style="padding:0 24px">
  <h2 style="color:#1B2559;font-size:16px;margin:16px 0 12px">Ce que <strong>SOS Hub Canada</strong> peut faire pour vous</h2>
  <table style="width:100%;border-collapse:collapse">
    ${[
      { n: '1', t: 'Analyse approfondie de votre admissibilité à tous les programmes' },
      { n: '2', t: 'Jumelage avec un employeur partenaire pour un permis de travail' },
      { n: '3', t: 'Préparation et dépôt de votre demande auprès d\'IRCC' },
      { n: '4', t: 'Suivi complet jusqu\'à l\'obtention de votre visa' },
    ].map(s => `<tr>
      <td style="padding:6px 10px 6px 0;vertical-align:top;width:32px">
        <div style="width:24px;height:24px;background:#D4A03C;border-radius:50%;text-align:center;line-height:24px;color:#FFF;font-size:12px;font-weight:800">${s.n}</div>
      </td>
      <td style="padding:6px 0;color:#4B5563;font-size:13px;line-height:1.4">${s.t}</td>
    </tr>`).join('')}
  </table>
</div>

<!-- ═══ OFFRE 49,99 $ ═══ -->
<div style="margin:24px;background-color:#1B2559;border-radius:16px;padding:28px;text-align:center">
  <div style="display:inline-block;background-color:#D4A03C;color:#FFF;font-size:10px;font-weight:800;padding:4px 16px;border-radius:20px;text-transform:uppercase;letter-spacing:2px;margin-bottom:12px">Offre spéciale</div>
  <h2 style="color:#FFF;font-size:20px;font-weight:900;margin:0 0 8px">Rapport complet + Consultation gratuite</h2>
  <p style="color:rgba(255,255,255,0.7);font-size:13px;margin:0 0 16px;line-height:1.5">
    Analyse détaillée de 12 programmes + plan personnalisé,<br>
    <strong style="color:#D4A03C">incluant 30 min de consultation gratuite</strong>
  </p>
  <div style="margin:16px 0">
    <span style="color:rgba(255,255,255,0.4);font-size:14px;text-decoration:line-through">149,99 $</span>
    <span style="color:#D4A03C;font-size:36px;font-weight:900;margin:0 8px">49,99 $</span>
  </div>
  <a href="https://soshubca.vercel.app/achat-rapport?plan=analyse-premium&name=${encodeURIComponent(fullName)}&email=${encodeURIComponent(client.email || '')}"
     style="display:inline-block;background-color:#D4A03C;color:#FFF;font-size:16px;font-weight:900;padding:16px 40px;border-radius:12px;text-decoration:none">
    Obtenir mon rapport — 49,99 $
  </a>
  <div style="margin-top:8px;color:rgba(255,255,255,0.3);font-size:10px">Paiement sécurisé par Square | ⚡ Expire dans 72h</div>
</div>

<!-- CONTACT -->
<div style="padding:16px 24px;text-align:center">
  <div style="color:#9CA3AF;font-size:12px;margin-bottom:12px">— ou contactez-nous —</div>
  <a href="https://wa.me/14386302869?text=${encodeURIComponent(`Bonjour, je suis ${fullName}. J'ai reçu mes résultats ${systemLabel} et j'aimerais en discuter.`)}"
     style="display:inline-block;background:#25D366;color:#FFF;font-size:14px;font-weight:800;padding:12px 28px;border-radius:12px;text-decoration:none;margin-bottom:8px">WhatsApp</a>
  &nbsp;
  <a href="mailto:info@soshubcanada.com?subject=${encodeURIComponent(`Résultats ${systemLabel} - ${fullName}`)}"
     style="display:inline-block;background:#1B2559;color:#FFF;font-size:14px;font-weight:700;padding:12px 28px;border-radius:12px;text-decoration:none">Courriel</a>
  <div style="margin-top:12px;color:#9CA3AF;font-size:11px">
    <strong style="color:#1B2559">SOS Hub Canada</strong><br>
    +1 (438) 630-2869 | info@soshubcanada.com<br>
    3737 Crémazie Est #402, Montréal QC H1Z 2K4
  </div>
</div>

<!-- FOOTER -->
<div style="background:#1B2559;padding:24px;text-align:center">
  <div style="font-size:18px;font-weight:900;color:#FFF">SOS <span style="color:#D4A03C">Hub</span> Canada</div>
  <div style="color:rgba(255,255,255,0.4);font-size:10px;margin-top:8px">Immigration — Consultation — Accompagnement</div>
</div>

</div></body></html>`;

  return { subject, body };
}

const KANBAN_STATUSES: CaseStatus[] = [
  'nouveau', 'consultation', 'en_preparation', 'formulaires_remplis',
  'revision', 'soumis', 'en_traitement_ircc',
];

const FORM_STATUS_COLORS: Record<string, string> = {
  vide: 'bg-gray-100 text-gray-600',
  en_cours: 'bg-amber-100 text-amber-700',
  rempli: 'bg-blue-100 text-blue-700',
  revise: 'bg-purple-100 text-purple-700',
  approuve: 'bg-green-100 text-green-700',
  signe: 'bg-emerald-100 text-emerald-800',
};

const TIMELINE_TYPE_LABELS: Record<string, string> = {
  note: 'Note',
  status_change: 'Changement de statut',
  form_update: 'Mise a jour formulaire',
  document: 'Document',
  appointment: 'Rendez-vous',
  email: 'Courriel',
  ircc_update: 'Mise a jour IRCC',
};

export default function DossiersPage() {
  const { currentUser, clients, cases, setCases, contracts, setContracts } = useCrm();
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [priorityFilter, setPriorityFilter] = useState('');
  const [viewMode, setViewMode] = useState<'kanban' | 'list'>('kanban');
  const [selectedCase, setSelectedCase] = useState<Case | null>(null);
  const [showNewModal, setShowNewModal] = useState(false);

  // New case form state
  const [newClientId, setNewClientId] = useState('');
  const [newProgramId, setNewProgramId] = useState('');
  const [newTitle, setNewTitle] = useState('');
  const [newPriority, setNewPriority] = useState<'basse' | 'normale' | 'haute' | 'urgente'>('normale');
  const [newDeadline, setNewDeadline] = useState('');
  const [newAssignedTo, setNewAssignedTo] = useState('');
  const [newAssignedLawyer, setNewAssignedLawyer] = useState('');
  const [newNotes, setNewNotes] = useState('');
  const [newLocation, setNewLocation] = useState<'canada' | 'etranger'>('canada');
  const [newCaseError, setNewCaseError] = useState<string | null>(null);
  const [emailSent, setEmailSent] = useState<string | null>(null);
  const [showEmailPreview, setShowEmailPreview] = useState(false);

  // --- Task management state ---
  const [allTasks, setAllTasks] = useState<CaseTask[]>([]);
  const [showTaskForm, setShowTaskForm] = useState(false);
  const [newTaskTitle, setNewTaskTitle] = useState('');
  const [newTaskAssignee, setNewTaskAssignee] = useState('');
  const [newTaskDueDate, setNewTaskDueDate] = useState('');
  const [newTaskPriority, setNewTaskPriority] = useState<TaskPriority>('moyenne');

  useEffect(() => {
    setAllTasks(loadTasks());
  }, []);

  const toggleTaskStatus = (taskId: string) => {
    setAllTasks(prev => {
      const updated = prev.map(t => {
        if (t.id !== taskId) return t;
        const nextStatus: TaskStatus = t.status === 'a_faire' ? 'en_cours' : t.status === 'en_cours' ? 'terminee' : 'a_faire';
        return { ...t, status: nextStatus };
      });
      saveTasks(updated);
      return updated;
    });
  };

  const addTask = () => {
    if (!newTaskTitle || !selectedCase) return;
    const task: CaseTask = {
      id: `task_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
      caseId: selectedCase.id,
      title: newTaskTitle,
      assignee: newTaskAssignee || currentUser?.id || '',
      dueDate: newTaskDueDate,
      priority: newTaskPriority,
      status: 'a_faire',
      createdAt: new Date().toISOString().split('T')[0],
    };
    setAllTasks(prev => {
      const updated = [...prev, task];
      saveTasks(updated);
      return updated;
    });
    setNewTaskTitle('');
    setNewTaskAssignee('');
    setNewTaskDueDate('');
    setNewTaskPriority('moyenne');
    setShowTaskForm(false);
  };

  if (!currentUser) return (
    <div className="flex items-center justify-center min-h-[60vh]">
      <div className="flex flex-col items-center gap-3">
        <FolderOpen size={32} className="animate-pulse text-[#D4A03C]" />
        <p className="text-sm text-gray-500">Chargement des dossiers...</p>
      </div>
    </div>
  );
  const perms = ROLE_PERMISSIONS[currentUser.role];

  const getClientName = (clientId: string) => {
    const c = clients.find(cl => cl.id === clientId);
    return c ? `${c.firstName} ${c.lastName}` : 'Client inconnu';
  };

  const getProgramName = (programId: string) => {
    return IMMIGRATION_PROGRAMS.find(p => p.id === programId)?.name ?? 'Programme inconnu';
  };

  const filtered = cases.filter(c => {
    const clientName = getClientName(c.clientId);
    const programName = getProgramName(c.programId);
    const matchSearch = `${c.title} ${clientName} ${programName} ${c.irccAppNumber} ${c.uciNumber}`
      .toLowerCase().includes(search.toLowerCase());
    const matchStatus = !statusFilter || c.status === statusFilter;
    const matchPriority = !priorityFilter || c.priority === priorityFilter;
    return matchSearch && matchStatus && matchPriority;
  });

  const getFormProgress = (forms: CaseForm[]) => {
    if (forms.length === 0) return null;
    const done = forms.filter(f => ['rempli', 'revise', 'approuve', 'signe'].includes(f.status)).length;
    return { done, total: forms.length, pct: Math.round((done / forms.length) * 100) };
  };

  const isOverdue = (deadline: string) => {
    if (!deadline) return false;
    return new Date(deadline) < new Date();
  };

  const resetNewForm = () => {
    setNewClientId('');
    setNewProgramId('');
    setNewTitle('');
    setNewPriority('normale');
    setNewDeadline('');
    setNewAssignedTo(currentUser.id);
    setNewAssignedLawyer('');
    setNewNotes('');
    setNewLocation('canada');
  };

  const openNewModal = () => {
    resetNewForm();
    setNewCaseError(null);
    setNewAssignedTo(currentUser.id);
    setShowNewModal(true);
  };

  // --- Scoring automatique pour le dossier sélectionné ---
  const selectedCaseScoring = useMemo(() => {
    if (!selectedCase) return null;
    const type = isScoringProgram(selectedCase.programId);
    if (!type) return null;
    const client = clients.find(c => c.id === selectedCase.clientId);
    if (!client) return null;

    const profile = buildProfileFromClient(client);
    const programName = getProgramName(selectedCase.programId);

    if (type === 'crs') {
      const breakdown = calculateCRS(profile);
      const advice = getCrsImprovementAdvice(profile, breakdown);
      const latestCutoff = CRS_RECENT_CUTOFFS.find(c => c.program === 'Général')?.score ?? 520;
      return { type, score: breakdown.total, threshold: latestCutoff, breakdown, advice, programName, client, profile };
    } else {
      const breakdown = calculateMIFI(profile);
      const advice = getMifiImprovementAdvice(profile, breakdown);
      return { type, score: breakdown.total, threshold: MIFI_THRESHOLD_ESTIMATE, breakdown, advice, programName, client, profile };
    }
  }, [selectedCase, clients]);

  // --- Envoyer le courriel de résultats via API ---
  const sendScoringEmail = async () => {
    if (!selectedCaseScoring || !selectedCase) return;
    const { type, score, threshold, advice, programName, client } = selectedCaseScoring;
    const email = generateScoringEmail(client, type, score, threshold, advice, programName);

    // Envoyer via API
    try {
      const res = await crmFetch('/api/crm/send-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          toEmail: client.email,
          subject: email.subject,
          emailBody: email.body,
          from_name: 'SOS Hub Canada',
          reply_to: 'info@soshubcanada.com',
          type: 'scoring_results',
        }),
      });
      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        console.error('Erreur envoi:', errData);
        alert('Erreur lors de l\'envoi du courriel. Veuillez reessayer.');
        setShowEmailPreview(false);
        return;
      }
    } catch (err) {
      console.error('Erreur envoi courriel:', err);
      setEmailSent(null);
      setShowEmailPreview(false);
      alert('Erreur lors de l\'envoi du courriel. Veuillez reessayer.');
      return;
    }

    setEmailSent(client.email);
    setShowEmailPreview(false);

    // Ajouter à la timeline du dossier
    const today = new Date().toISOString().split('T')[0];
    const updatedCase = { ...selectedCase };
    updatedCase.timeline = [...updatedCase.timeline, {
      id: `t${Date.now()}-email`,
      date: today,
      type: 'email' as const,
      description: `Courriel de résultats ${type === 'crs' ? 'CRS' : 'MIFI'} envoyé à ${client.email} — Score: ${score} pts${score >= threshold ? ' (qualifié)' : ''}`,
      userId: currentUser.id,
    }];
    setCases(cases.map(c => c.id === selectedCase.id ? updatedCase : c));
    setSelectedCase(updatedCase);

    // Fermer la notification après 4 secondes
    setTimeout(() => setEmailSent(null), 4000);
  };

  const saveNewCase = () => {
    // Validation with visible error messages
    if (!newClientId) {
      setNewCaseError('Veuillez selectionner un client');
      return;
    }
    if (!newProgramId) {
      setNewCaseError('Veuillez selectionner un programme d\'immigration');
      return;
    }
    if (!newTitle.trim()) {
      setNewCaseError('Le titre du dossier est requis');
      return;
    }
    if (newDeadline) {
      const deadlineDate = new Date(newDeadline);
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      if (deadlineDate < today) {
        setNewCaseError('L\'echeance ne peut pas etre dans le passe');
        return;
      }
    }
    setNewCaseError(null);
    const selectedProgram = IMMIGRATION_PROGRAMS.find(p => p.id === newProgramId);
    if (!selectedProgram) return;

    const requiredFormIds = selectedProgram.requiredForms;
    const forms: CaseForm[] = requiredFormIds.map(fId => ({
      id: `cf${Date.now()}-${fId}`,
      formId: fId,
      status: 'vide' as const,
      filledBy: '', reviewedBy: '', approvedBy: '',
      data: {}, lastUpdated: new Date().toISOString().split('T')[0],
    }));

    const today = new Date().toISOString().split('T')[0];
    const caseId = `case${Date.now()}`;
    const newCase: Case = {
      id: caseId,
      clientId: newClientId,
      programId: newProgramId,
      title: newTitle,
      status: 'nouveau',
      assignedTo: newAssignedTo || currentUser.id,
      assignedLawyer: newAssignedLawyer,
      priority: newPriority,
      createdAt: today,
      updatedAt: today,
      deadline: newDeadline,
      irccAppNumber: '',
      uciNumber: '',
      notes: newNotes,
      forms,
      timeline: [{
        id: `t${Date.now()}`,
        date: today,
        type: 'note',
        description: `Dossier créé — Frais d'ouverture: ${FRAIS_OUVERTURE_DOSSIER} $`,
        userId: currentUser.id,
      }],
    };

    // Auto-générer le contrat de service lié au dossier
    const contract = generateContractFromCase({
      caseId,
      clientId: newClientId,
      programId: newProgramId,
      createdBy: currentUser.id,
      location: newLocation,
      fraisOuverturePaye: true, // Les frais d'ouverture sont déduits du contrat
    });

    // Auto-scoring si programme EE ou PSTQ
    const scoringType = isScoringProgram(newProgramId);
    if (scoringType) {
      const client = clients.find(c => c.id === newClientId);
      if (client) {
        const profile = buildProfileFromClient(client);
        const score = scoringType === 'crs' ? calculateCRS(profile).total : calculateMIFI(profile).total;
        const threshold = scoringType === 'crs'
          ? (CRS_RECENT_CUTOFFS.find(c => c.program === 'Général')?.score ?? 520)
          : MIFI_THRESHOLD_ESTIMATE;
        const label = scoringType === 'crs' ? 'CRS (Entrée express)' : 'MIFI (PSTQ/Arrima)';
        newCase.timeline.push({
          id: `t${Date.now()}-scoring`,
          date: today,
          type: 'note',
          description: `Analyse ${label} automatique — Score: ${score} pts (seuil: ${threshold})${score >= threshold ? ' ✓ Qualifié' : ` — ${threshold - score} pts à améliorer`}`,
          userId: currentUser.id,
        });
      }
    }

    setCases([...cases, newCase]);
    if (contract) {
      setContracts([...contracts, contract]);
      // Ajouter un événement timeline pour le contrat
      newCase.timeline.push({
        id: `t${Date.now()}-contract`,
        date: today,
        type: 'note',
        description: `Contrat de service généré automatiquement — ${contract.grandTotal.toLocaleString('fr-CA', { style: 'currency', currency: 'CAD' })} (frais d'ouverture de ${FRAIS_OUVERTURE_DOSSIER} $ déduits)`,
        userId: currentUser.id,
      });
    }
    // Auto-generate tasks from program template
    const autoTasks = generateTasksForProgram(
      newProgramId,
      caseId,
      newAssignedTo || currentUser.id,
    );
    if (autoTasks.length > 0) {
      const existingTasks = loadTasks();
      const newTasks: CaseTask[] = autoTasks.map(t => ({
        ...t,
        autoGenerated: true,
      }));
      const merged = [...existingTasks, ...newTasks];
      saveTasks(merged);
      setAllTasks(merged);

      const config = getTaskConfigForProgram(newProgramId);
      newCase.timeline.push({
        id: `t${Date.now()}-tasks`,
        date: today,
        type: 'note',
        description: `${newTasks.length} tâches auto-générées pour ${selectedProgram.name}${config ? ` — Délai estimé: ${config.estimatedTimeline}` : ''}`,
        userId: currentUser.id,
      });
    }

    setShowNewModal(false);
  };

  // Group programs by category for dropdown
  const programsByCategory = Object.entries(PROGRAM_CATEGORIES).map(([catId, catLabel]) => ({
    catId,
    catLabel,
    programs: IMMIGRATION_PROGRAMS.filter(p => p.category === catId),
  })).filter(g => g.programs.length > 0);

  return (
    <div className="space-y-6">
      {/* En-tete */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <FolderOpen size={24} className="text-[#D4A03C]" />
          <h1 className="text-2xl font-bold text-gray-900">Gestion des dossiers</h1>
          <span className="text-sm text-gray-500">({filtered.length} dossiers)</span>
        </div>
        {perms.canCreateCase && (
          <button
            onClick={openNewModal}
            className="flex items-center gap-2 px-4 py-2 bg-[#D4A03C] text-white rounded-lg font-medium hover:bg-[#B8892F] transition-colors"
          >
            <Plus size={16} /> Nouveau dossier
          </button>
        )}
      </div>

      {/* Barre de filtres */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="relative flex-1 min-w-[240px]">
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
          <input
            type="text"
            placeholder="Rechercher un dossier, client, programme..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="w-full pl-9 pr-4 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#D4A03C]/30 focus:border-[#D4A03C]"
          />
        </div>
        <div className="flex items-center gap-1">
          <Filter size={14} className="text-gray-400" />
          <select
            value={statusFilter}
            onChange={e => setStatusFilter(e.target.value)}
            className="px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#D4A03C]/30"
          >
            <option value="">Tous les statuts</option>
            {Object.entries(CASE_STATUS_LABELS).map(([k, v]) => (
              <option key={k} value={k}>{v}</option>
            ))}
          </select>
        </div>
        <select
          value={priorityFilter}
          onChange={e => setPriorityFilter(e.target.value)}
          className="px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#D4A03C]/30"
        >
          <option value="">Toutes les priorites</option>
          {Object.entries(PRIORITY_LABELS).map(([k, v]) => (
            <option key={k} value={k}>{v}</option>
          ))}
        </select>
        <div className="flex items-center gap-1 ml-auto bg-gray-100 rounded-lg p-0.5">
          <button
            onClick={() => setViewMode('kanban')}
            className={`p-2 rounded-md transition-colors ${viewMode === 'kanban' ? 'bg-white text-[#1B2559] shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
            title="Vue Kanban"
          >
            <LayoutGrid size={16} />
          </button>
          <button
            onClick={() => setViewMode('list')}
            className={`p-2 rounded-md transition-colors ${viewMode === 'list' ? 'bg-white text-[#1B2559] shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
            title="Vue Liste"
          >
            <List size={16} />
          </button>
        </div>
      </div>

      {/* Empty state global */}
      {filtered.length === 0 && !selectedCase && (
        <div className="bg-white rounded-xl border border-gray-200 p-12 text-center">
          {search || statusFilter || priorityFilter ? (
            <>
              <Search size={40} className="mx-auto mb-3 text-gray-300" />
              <p className="text-sm font-medium text-gray-500">Aucun dossier ne correspond aux filtres</p>
              <p className="text-xs text-gray-400 mt-1">Modifiez vos criteres de recherche ou reinitialiser les filtres</p>
              <button onClick={() => { setSearch(''); setStatusFilter(''); setPriorityFilter(''); }} className="mt-3 text-xs text-[#D4A03C] font-medium hover:underline">Reinitialiser les filtres</button>
            </>
          ) : (
            <>
              <FolderOpen size={40} className="mx-auto mb-3 text-gray-300" />
              <p className="text-sm font-medium text-gray-500">Aucun dossier pour le moment</p>
              <p className="text-xs text-gray-400 mt-1">Creez un nouveau dossier pour commencer le suivi d&apos;un client</p>
              {perms.canCreateCase && (
                <button onClick={openNewModal} className="mt-4 inline-flex items-center gap-2 px-4 py-2 bg-[#D4A03C] text-white rounded-lg text-sm font-medium hover:bg-[#B8892F] transition-colors">
                  <Plus size={16} /> Nouveau dossier
                </button>
              )}
            </>
          )}
        </div>
      )}

      {/* Vue Kanban */}
      {viewMode === 'kanban' && filtered.length > 0 && (
        <div className="flex gap-4 overflow-x-auto pb-4">
          {KANBAN_STATUSES.map(status => {
            const columnCases = filtered.filter(c => c.status === status);
            return (
              <div key={status} className="flex-shrink-0 w-72">
                <div className="flex items-center justify-between mb-3 px-1">
                  <div className="flex items-center gap-2">
                    <span className={`inline-block w-2.5 h-2.5 rounded-full ${CASE_STATUS_COLORS[status].replace(/text-\S+/, '').replace('bg-', 'bg-').trim().split(' ')[0]}`} />
                    <span className="text-sm font-semibold text-gray-700">
                      {CASE_STATUS_LABELS[status]}
                    </span>
                  </div>
                  <span className="text-xs font-medium text-gray-400 bg-gray-100 px-2 py-0.5 rounded-full">
                    {columnCases.length}
                  </span>
                </div>
                <div className="space-y-2">
                  {columnCases.length === 0 && (
                    <div className="border-2 border-dashed border-gray-200 rounded-lg p-4 text-center text-xs text-gray-400">
                      Aucun dossier
                    </div>
                  )}
                  {columnCases.map(c => {
                    const progress = getFormProgress(c.forms);
                    const overdue = isOverdue(c.deadline);
                    return (
                      <div
                        key={c.id}
                        onClick={() => setSelectedCase(c)}
                        className="bg-white border border-gray-200 rounded-lg p-3 cursor-pointer hover:shadow-md hover:border-[#D4A03C]/30 transition-all"
                      >
                        <div className="flex items-start justify-between mb-2">
                          <h4 className="text-sm font-semibold text-gray-800 line-clamp-2 leading-tight">
                            {c.title}
                          </h4>
                          <span className={`ml-2 flex-shrink-0 text-[10px] font-medium px-1.5 py-0.5 rounded ${PRIORITY_COLORS[c.priority]}`}>
                            {PRIORITY_LABELS[c.priority]}
                          </span>
                        </div>
                        <p className="text-xs text-gray-500 mb-1">{getClientName(c.clientId)}</p>
                        <p className="text-xs text-gray-400 mb-2 line-clamp-1">{getProgramName(c.programId)}</p>
                        {progress && (
                          <div className="mb-2">
                            <div className="flex items-center justify-between text-[10px] text-gray-500 mb-1">
                              <span>Formulaires</span>
                              <span>{progress.done}/{progress.total}</span>
                            </div>
                            <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
                              <div
                                className="h-full bg-[#D4A03C] rounded-full transition-all"
                                style={{ width: `${progress.pct}%` }}
                              />
                            </div>
                          </div>
                        )}
                        <div className="flex items-center gap-2">
                          {c.deadline && (
                            <div className={`flex items-center gap-1 text-[10px] ${overdue ? 'text-red-600' : 'text-gray-400'}`}>
                              {overdue ? <AlertTriangle size={10} /> : <Clock size={10} />}
                              <span>{overdue ? 'En retard' : 'Echeance'}: {c.deadline}</span>
                            </div>
                          )}
                          {getTaskCountForCase(c.id, allTasks) > 0 && (
                            <span className="ml-auto flex items-center gap-0.5 text-[10px] font-medium px-1.5 py-0.5 rounded bg-indigo-100 text-indigo-700">
                              <ListChecks size={10} />{getTaskCountForCase(c.id, allTasks)}
                            </span>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Vue Liste */}
      {viewMode === 'list' && filtered.length > 0 && (
        <div className="bg-white border border-gray-200 rounded-xl overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 border-b border-gray-200">
                  <th className="text-left px-4 py-3 font-semibold text-gray-600">Dossier</th>
                  <th className="text-left px-4 py-3 font-semibold text-gray-600">Client</th>
                  <th className="text-left px-4 py-3 font-semibold text-gray-600">Programme</th>
                  <th className="text-left px-4 py-3 font-semibold text-gray-600">Statut</th>
                  <th className="text-left px-4 py-3 font-semibold text-gray-600">Priorite</th>
                  <th className="text-left px-4 py-3 font-semibold text-gray-600">Assigne</th>
                  <th className="text-left px-4 py-3 font-semibold text-gray-600">Echeance</th>
                  <th className="text-center px-4 py-3 font-semibold text-gray-600">Actions</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map(c => {
                  const overdue = isOverdue(c.deadline);
                  return (
                    <tr
                      key={c.id}
                      className="border-b border-gray-100 hover:bg-[#EAEDF5]/30 cursor-pointer transition-colors"
                      onClick={() => setSelectedCase(c)}
                    >
                      <td className="px-4 py-3">
                        <div className="font-medium text-gray-800">{c.title}</div>
                        <div className="text-xs text-gray-400">{c.id}</div>
                      </td>
                      <td className="px-4 py-3 text-gray-700">{getClientName(c.clientId)}</td>
                      <td className="px-4 py-3">
                        <span className="text-xs text-gray-600 line-clamp-1">{getProgramName(c.programId)}</span>
                      </td>
                      <td className="px-4 py-3">
                        <span className={`text-xs font-medium px-2 py-1 rounded-full ${CASE_STATUS_COLORS[c.status]}`}>
                          {CASE_STATUS_LABELS[c.status]}
                        </span>
                      </td>
                      <td className="px-4 py-3">
                        <span className={`text-xs font-medium px-2 py-1 rounded-full ${PRIORITY_COLORS[c.priority]}`}>
                          {PRIORITY_LABELS[c.priority]}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-gray-600 text-xs">{getUserName(c.assignedTo)}</td>
                      <td className="px-4 py-3">
                        {c.deadline ? (
                          <span className={`flex items-center gap-1 text-xs ${overdue ? 'text-red-600 font-medium' : 'text-gray-500'}`}>
                            {overdue && <AlertTriangle size={12} />}
                            {c.deadline}
                          </span>
                        ) : (
                          <span className="text-xs text-gray-300">-</span>
                        )}
                      </td>
                      <td className="px-4 py-3 text-center">
                        <button
                          onClick={e => { e.stopPropagation(); setSelectedCase(c); }}
                          className="text-[#D4A03C] hover:text-[#1B2559] transition-colors"
                          title="Voir le detail"
                        >
                          <Eye size={16} />
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Panneau de detail - slide-out droite */}
      {selectedCase && (
        <div className="fixed inset-0 z-50 flex justify-end">
          <div className="absolute inset-0 bg-black/30" onClick={() => setSelectedCase(null)} />
          <div className="relative w-full max-w-lg bg-white shadow-2xl overflow-y-auto animate-in slide-in-from-right">
            {/* En-tete du panneau */}
            <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex items-start justify-between z-10">
              <div className="flex-1 min-w-0">
                <h2 className="text-lg font-bold text-gray-900 truncate">{selectedCase.title}</h2>
                <div className="flex items-center gap-2 mt-1">
                  <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${CASE_STATUS_COLORS[selectedCase.status]}`}>
                    {CASE_STATUS_LABELS[selectedCase.status]}
                  </span>
                  <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${PRIORITY_COLORS[selectedCase.priority]}`}>
                    {PRIORITY_LABELS[selectedCase.priority]}
                  </span>
                </div>
              </div>
              <button
                onClick={() => setSelectedCase(null)}
                className="ml-4 p-1 rounded-md hover:bg-gray-100 text-gray-400 hover:text-gray-600 transition-colors"
              >
                <X size={20} />
              </button>
            </div>

            <div className="px-6 py-5 space-y-6">
              {/* Client */}
              <section>
                <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Client</h3>
                <p className="text-sm font-medium text-gray-800">{getClientName(selectedCase.clientId)}</p>
                {(() => {
                  const cl = clients.find(c => c.id === selectedCase.clientId);
                  if (!cl) return null;
                  return (
                    <div className="text-xs text-gray-500 mt-1 space-y-0.5">
                      <p>{cl.email} / {cl.phone}</p>
                      <p>{cl.nationality} - {cl.currentStatus}</p>
                    </div>
                  );
                })()}
              </section>

              {/* Programme */}
              <section>
                <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Programme</h3>
                <p className="text-sm text-gray-700">{getProgramName(selectedCase.programId)}</p>
              </section>

              {/* Analyse de scoring automatique (EE / PSTQ) */}
              {selectedCaseScoring && (
                <section className={`rounded-xl p-4 border ${
                  selectedCaseScoring.score >= selectedCaseScoring.threshold
                    ? 'bg-green-50 border-green-200'
                    : 'bg-amber-50 border-amber-200'
                }`}>
                  <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center gap-2">
                      <Calculator size={16} className="text-[#1B2559]" />
                      <h3 className="text-xs font-semibold text-[#1B2559] uppercase tracking-wider">
                        Analyse {selectedCaseScoring.type === 'crs' ? 'CRS' : 'MIFI'} automatique
                      </h3>
                    </div>
                    <Link
                      href="/crm/analyse-scoring"
                      className="text-[10px] text-[#D4A03C] hover:text-[#1B2559] font-medium"
                    >
                      Analyse détaillée →
                    </Link>
                  </div>

                  {/* Score */}
                  <div className="flex items-center gap-4 mb-3">
                    <div className="text-center">
                      <div className={`text-3xl font-bold ${
                        selectedCaseScoring.score >= selectedCaseScoring.threshold ? 'text-green-600' : 'text-amber-600'
                      }`}>
                        {selectedCaseScoring.score}
                      </div>
                      <div className="text-[10px] text-gray-500">
                        / {selectedCaseScoring.type === 'crs' ? '1200' : '100'} pts
                      </div>
                    </div>
                    <div className="flex-1">
                      <div className="h-2.5 bg-white rounded-full overflow-hidden">
                        <div
                          className={`h-full rounded-full transition-all ${
                            selectedCaseScoring.score >= selectedCaseScoring.threshold ? 'bg-green-500' : 'bg-amber-500'
                          }`}
                          style={{ width: `${Math.min((selectedCaseScoring.score / (selectedCaseScoring.type === 'crs' ? 1200 : 100)) * 100, 100)}%` }}
                        />
                      </div>
                      <div className="flex items-center justify-between mt-1">
                        {selectedCaseScoring.score >= selectedCaseScoring.threshold ? (
                          <span className="text-[10px] text-green-700 font-medium flex items-center gap-1">
                            <CheckCircle size={10} /> Au-dessus du seuil ({selectedCaseScoring.threshold})
                          </span>
                        ) : (
                          <span className="text-[10px] text-amber-700 font-medium flex items-center gap-1">
                            <Target size={10} /> {selectedCaseScoring.threshold - selectedCaseScoring.score} pts sous le seuil ({selectedCaseScoring.threshold})
                          </span>
                        )}
                      </div>
                    </div>
                  </div>

                  {/* Top 3 conseils */}
                  {selectedCaseScoring.advice.filter(a => a.actionable).length > 0 && (
                    <div className="mb-3">
                      <div className="flex items-center gap-1 mb-2">
                        <Lightbulb size={12} className="text-[#D4A03C]" />
                        <span className="text-[10px] font-semibold text-gray-600 uppercase tracking-wider">Recommandations prioritaires</span>
                      </div>
                      <div className="space-y-1.5">
                        {selectedCaseScoring.advice.filter(a => a.actionable).slice(0, 3).map((a, i) => (
                          <div key={i} className="bg-white rounded-lg px-3 py-2 text-xs flex items-start gap-2">
                            <span className={`shrink-0 w-4 h-4 rounded-full flex items-center justify-center text-[10px] font-bold ${
                              a.impact === 'très_élevé' ? 'bg-red-100 text-red-600' :
                              a.impact === 'élevé' ? 'bg-orange-100 text-orange-600' :
                              'bg-yellow-100 text-yellow-600'
                            }`}>{i + 1}</span>
                            <div className="flex-1 min-w-0">
                              <span className="font-medium text-gray-800">{a.category}</span>
                              <span className="text-gray-400 ml-1">({a.currentPoints}/{a.maxPoints})</span>
                              <p className="text-gray-500 mt-0.5 line-clamp-2">{a.advice}</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Boutons d'action */}
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => setShowEmailPreview(true)}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-[#1B2559] text-white text-xs font-medium rounded-lg hover:bg-[#2A3670] transition-colors"
                    >
                      <Mail size={12} />
                      Envoyer les résultats au client
                    </button>
                    <Link
                      href="/crm/analyse-scoring"
                      className="flex items-center gap-1.5 px-3 py-1.5 border border-gray-300 text-gray-700 text-xs font-medium rounded-lg hover:bg-white transition-colors"
                    >
                      <TrendingUp size={12} />
                      Simuler des améliorations
                    </Link>
                  </div>
                </section>
              )}

              {/* Modal aperçu courriel */}
              {showEmailPreview && selectedCaseScoring && (
                <div className="fixed inset-0 z-[60] flex items-center justify-center">
                  <div className="absolute inset-0 bg-black/40" onClick={() => setShowEmailPreview(false)} />
                  <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-lg mx-4 max-h-[80vh] overflow-hidden flex flex-col">
                    <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Mail size={18} className="text-[#1B2559]" />
                        <h3 className="font-bold text-gray-900">Envoyer les résultats par courriel</h3>
                      </div>
                      <button onClick={() => setShowEmailPreview(false)} className="p-1 hover:bg-gray-100 rounded-md text-gray-400">
                        <X size={18} />
                      </button>
                    </div>
                    <div className="px-6 py-4 flex-1 overflow-y-auto">
                      <div className="mb-4">
                        <label className="text-xs font-medium text-gray-500">Destinataire</label>
                        <div className="flex items-center gap-2 mt-1">
                          <div className="w-8 h-8 rounded-full bg-[#EAEDF5] text-[#1B2559] flex items-center justify-center text-xs font-bold">
                            {selectedCaseScoring.client.firstName[0]}{selectedCaseScoring.client.lastName[0]}
                          </div>
                          <div>
                            <div className="text-sm font-medium text-gray-800">{selectedCaseScoring.client.firstName} {selectedCaseScoring.client.lastName}</div>
                            <div className="text-xs text-gray-500">{selectedCaseScoring.client.email}</div>
                          </div>
                        </div>
                      </div>
                      {(() => {
                        const email = generateScoringEmail(
                          selectedCaseScoring.client,
                          selectedCaseScoring.type,
                          selectedCaseScoring.score,
                          selectedCaseScoring.threshold,
                          selectedCaseScoring.advice,
                          selectedCaseScoring.programName,
                        );
                        return (
                          <>
                            <div className="mb-3">
                              <label className="text-xs font-medium text-gray-500">Objet</label>
                              <p className="text-sm font-medium text-gray-800 mt-1">{email.subject}</p>
                            </div>
                            <div>
                              <label className="text-xs font-medium text-gray-500">Aperçu du message</label>
                              <pre className="mt-2 bg-gray-50 border border-gray-200 rounded-lg p-4 text-xs text-gray-700 whitespace-pre-wrap font-sans leading-relaxed max-h-[40vh] overflow-y-auto">
                                {email.body}
                              </pre>
                            </div>
                          </>
                        );
                      })()}
                    </div>
                    <div className="px-6 py-4 border-t border-gray-200 flex items-center justify-end gap-3">
                      <button
                        onClick={() => setShowEmailPreview(false)}
                        className="px-4 py-2 text-sm text-gray-600 hover:text-gray-800 transition-colors"
                      >
                        Annuler
                      </button>
                      <button
                        onClick={sendScoringEmail}
                        className="flex items-center gap-2 px-5 py-2 bg-[#D4A03C] text-white text-sm font-medium rounded-lg hover:bg-[#B8892F] transition-colors"
                      >
                        <Send size={14} />
                        Envoyer le courriel
                      </button>
                    </div>
                  </div>
                </div>
              )}

              {/* Contrat lié */}
              {(() => {
                const linkedContract = contracts.find(ct => ct.caseId === selectedCase.id);
                if (!linkedContract) return null;
                return (
                  <section className="bg-[#F7F3E8] rounded-lg p-4 border border-[#D4A03C]/20">
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <FileSignature size={14} className="text-[#D4A03C]" />
                        <h3 className="text-xs font-semibold text-[#1B2559] uppercase tracking-wider">Contrat de service</h3>
                      </div>
                      <span className={`text-[10px] font-medium px-2 py-0.5 rounded-full ${
                        linkedContract.status === 'brouillon' ? 'bg-gray-100 text-gray-700' :
                        linkedContract.status === 'envoye' ? 'bg-blue-100 text-blue-700' :
                        linkedContract.status === 'signe' ? 'bg-green-100 text-green-700' :
                        linkedContract.status === 'actif' ? 'bg-indigo-100 text-indigo-700' :
                        'bg-gray-100 text-gray-700'
                      }`}>
                        {linkedContract.status === 'brouillon' ? 'Brouillon' :
                         linkedContract.status === 'envoye' ? 'Envoyé' :
                         linkedContract.status === 'signe' ? 'Signé' :
                         linkedContract.status === 'actif' ? 'Actif' : linkedContract.status}
                      </span>
                    </div>
                    <div className="grid grid-cols-2 gap-2 text-xs">
                      <div>
                        <span className="text-gray-500">Montant total</span>
                        <p className="font-bold text-[#D4A03C]">{linkedContract.grandTotal.toLocaleString('fr-CA', { style: 'currency', currency: 'CAD' })}</p>
                      </div>
                      <div>
                        <span className="text-gray-500">Versements</span>
                        <p className="font-medium text-gray-700">{linkedContract.installments.length} versement(s)</p>
                      </div>
                    </div>
                    <Link
                      href="/crm/contrats"
                      className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-[#D4A03C] hover:text-[#1B2559] transition-colors"
                    >
                      <DollarSign size={12} />
                      Voir le contrat
                    </Link>
                  </section>
                );
              })()}

              {/* Numeros */}
              <section className="grid grid-cols-2 gap-4">
                <div>
                  <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-1">UCI</h3>
                  <p className="text-sm text-gray-700">{selectedCase.uciNumber || '-'}</p>
                </div>
                <div>
                  <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-1">No. IRCC</h3>
                  <p className="text-sm text-gray-700">{selectedCase.irccAppNumber || '-'}</p>
                </div>
              </section>

              {/* Dates */}
              <section>
                <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Dates</h3>
                <div className="grid grid-cols-3 gap-3 text-xs">
                  <div>
                    <span className="text-gray-400">Creation</span>
                    <p className="text-gray-700 font-medium">{selectedCase.createdAt}</p>
                  </div>
                  <div>
                    <span className="text-gray-400">Derniere maj</span>
                    <p className="text-gray-700 font-medium">{selectedCase.updatedAt}</p>
                  </div>
                  <div>
                    <span className="text-gray-400">Echeance</span>
                    <p className={`font-medium ${isOverdue(selectedCase.deadline) ? 'text-red-600' : 'text-gray-700'}`}>
                      {selectedCase.deadline || '-'}
                    </p>
                  </div>
                </div>
              </section>

              {/* Assigne */}
              <section className="grid grid-cols-2 gap-4">
                <div>
                  <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-1">Assigne a</h3>
                  <p className="text-sm text-gray-700">{getUserName(selectedCase.assignedTo)}</p>
                </div>
                <div>
                  <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-1">Avocat</h3>
                  <p className="text-sm text-gray-700">{selectedCase.assignedLawyer ? getUserName(selectedCase.assignedLawyer) : '-'}</p>
                </div>
              </section>

              {/* Notes & Suivi */}
              <section>
                {selectedCase.notes && (
                  <div className="mb-3 p-3 bg-yellow-50 border border-yellow-200 rounded-lg">
                    <h4 className="text-xs font-semibold text-yellow-700 uppercase mb-1 flex items-center gap-1">
                      <Clock size={10} /> Note initiale
                    </h4>
                    <p className="text-sm text-gray-700">{selectedCase.notes}</p>
                  </div>
                )}
                <NotesSection
                  entityId={selectedCase.id}
                  entityType="dossier"
                  categories={DOSSIER_NOTE_CATEGORIES}
                  storageKey="soshub_dossier_notes"
                  currentUser={currentUser}
                  dossierId={selectedCase.id}
                  emptyMessage="Aucune note pour ce dossier"
                />
              </section>

              {/* Formulaires */}
              <section>
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
                    Formulaires ({selectedCase.forms.length})
                  </h3>
                  <Link
                    href={`/crm/formulaires?case=${selectedCase.id}`}
                    className="text-xs font-medium text-[#D4A03C] hover:text-[#1B2559] transition-colors"
                  >
                    Remplir les formulaires
                  </Link>
                </div>
                {selectedCase.forms.length === 0 ? (
                  <p className="text-xs text-gray-400">Aucun formulaire</p>
                ) : (
                  <div className="space-y-1.5">
                    {selectedCase.forms.map(f => (
                      <div key={f.id} className="flex items-center justify-between bg-gray-50 rounded-lg px-3 py-2">
                        <span className="text-xs font-medium text-gray-700">{f.formId.toUpperCase()}</span>
                        <span className={`text-[10px] font-medium px-2 py-0.5 rounded-full ${FORM_STATUS_COLORS[f.status] || 'bg-gray-100 text-gray-600'}`}>
                          {FORM_STATUS_LABELS[f.status] || f.status}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </section>

              {/* ═══ TÂCHES PREMIUM ═══ */}
              <section>
                {(() => {
                  const caseTasks = allTasks.filter(t => t.caseId === selectedCase.id);
                  const doneTasks = caseTasks.filter(t => t.status === 'terminee').length;
                  const totalTasks = caseTasks.length;
                  const pctDone = totalTasks > 0 ? Math.round((doneTasks / totalTasks) * 100) : 0;
                  const config = getTaskConfigForProgram(selectedCase.programId);

                  // Group by phase
                  const phases = ['preparation', 'documents', 'formulaires', 'revision', 'soumission', 'suivi'];
                  const tasksByPhase: Record<string, CaseTask[]> = {};
                  phases.forEach(p => { tasksByPhase[p] = []; });
                  tasksByPhase['autre'] = [];
                  caseTasks.forEach(t => {
                    const ph = t.phase && phases.includes(t.phase) ? t.phase : 'autre';
                    tasksByPhase[ph].push(t);
                  });

                  return (
                    <>
                      {/* Header */}
                      <div className="flex items-center justify-between mb-2">
                        <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider flex items-center gap-1">
                          <ListChecks size={12} />
                          Taches ({totalTasks})
                        </h3>
                        <div className="flex items-center gap-2">
                          {config && totalTasks === 0 && (
                            <button
                              onClick={() => {
                                const autoTasks = generateTasksForProgram(
                                  selectedCase.programId,
                                  selectedCase.id,
                                  selectedCase.assignedTo,
                                );
                                if (autoTasks.length > 0) {
                                  const newTasks: CaseTask[] = autoTasks.map(t => ({ ...t, autoGenerated: true }));
                                  const merged = [...allTasks, ...newTasks];
                                  saveTasks(merged);
                                  setAllTasks(merged);
                                }
                              }}
                              className="text-[10px] font-bold flex items-center gap-1 px-2 py-1 rounded-full bg-[#D4A03C]/10 text-[#D4A03C] border border-[#D4A03C]/20 hover:bg-[#D4A03C]/20 transition"
                            >
                              <Zap size={10} /> Auto-generer
                            </button>
                          )}
                          <button
                            onClick={() => setShowTaskForm(!showTaskForm)}
                            className="text-xs font-medium flex items-center gap-1 hover:opacity-80 transition-opacity"
                            style={{ color: '#D4A03C' }}
                          >
                            <Plus size={12} /> Ajouter
                          </button>
                        </div>
                      </div>

                      {/* Progress bar */}
                      {totalTasks > 0 && (
                        <div className="mb-3">
                          <div className="flex items-center justify-between text-[10px] mb-1">
                            <span className="text-gray-500">{doneTasks}/{totalTasks} terminées</span>
                            <span className="font-bold" style={{ color: pctDone >= 100 ? '#10B981' : '#D4A03C' }}>{pctDone}%</span>
                          </div>
                          <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
                            <div
                              className="h-full rounded-full transition-all duration-500"
                              style={{ width: `${pctDone}%`, backgroundColor: pctDone >= 100 ? '#10B981' : '#D4A03C' }}
                            />
                          </div>
                          {config && (
                            <div className="mt-1.5 flex items-center gap-1.5 text-[10px] text-gray-400">
                              <Clock size={10} />
                              <span>Délai estimé: {config.estimatedTimeline}</span>
                            </div>
                          )}
                        </div>
                      )}

                      {/* Add task form */}
                      {showTaskForm && (
                        <div className="bg-gray-50 rounded-lg p-3 mb-3 space-y-2 border border-gray-200">
                          <input
                            type="text"
                            value={newTaskTitle}
                            onChange={e => setNewTaskTitle(e.target.value)}
                            placeholder="Titre de la tache..."
                            className="w-full px-3 py-1.5 border border-gray-200 rounded text-xs focus:outline-none focus:ring-1 focus:ring-[#D4A03C]/30"
                          />
                          <div className="grid grid-cols-2 gap-2">
                            <select
                              value={newTaskAssignee}
                              onChange={e => setNewTaskAssignee(e.target.value)}
                              className="px-2 py-1.5 border border-gray-200 rounded text-xs focus:outline-none"
                            >
                              <option value="">Assigner a...</option>
                              {DEMO_USERS.map(u => (
                                <option key={u.id} value={u.id}>{u.name}</option>
                              ))}
                            </select>
                            <input
                              type="date"
                              value={newTaskDueDate}
                              onChange={e => setNewTaskDueDate(e.target.value)}
                              className="px-2 py-1.5 border border-gray-200 rounded text-xs focus:outline-none"
                            />
                          </div>
                          <div className="flex items-center gap-2">
                            <select
                              value={newTaskPriority}
                              onChange={e => setNewTaskPriority(e.target.value as TaskPriority)}
                              className="px-2 py-1.5 border border-gray-200 rounded text-xs focus:outline-none"
                            >
                              <option value="basse">Basse</option>
                              <option value="moyenne">Moyenne</option>
                              <option value="haute">Haute</option>
                            </select>
                            <div className="flex-1" />
                            <button onClick={() => setShowTaskForm(false)} className="text-xs text-gray-500 hover:text-gray-700 px-2 py-1">Annuler</button>
                            <button
                              onClick={addTask}
                              disabled={!newTaskTitle}
                              className="text-xs font-medium px-3 py-1.5 rounded text-white disabled:opacity-50"
                              style={{ backgroundColor: '#D4A03C' }}
                            >
                              Ajouter
                            </button>
                          </div>
                        </div>
                      )}

                      {/* Tasks grouped by phase */}
                      {totalTasks > 0 ? (
                        <div className="space-y-3">
                          {[...phases, 'autre'].map(phase => {
                            const pTasks = tasksByPhase[phase];
                            if (!pTasks || pTasks.length === 0) return null;
                            const phaseConf = PHASE_CONFIG[phase] || { label: 'Autres', color: 'text-gray-600', bg: 'bg-gray-50 border-gray-200' };
                            const phaseDone = pTasks.filter(t => t.status === 'terminee').length;

                            return (
                              <div key={phase}>
                                <div className="flex items-center gap-2 mb-1">
                                  <span className={`text-[10px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded border ${phaseConf.bg} ${phaseConf.color}`}>
                                    {phaseConf.label}
                                  </span>
                                  <span className="text-[10px] text-gray-400">{phaseDone}/{pTasks.length}</span>
                                </div>
                                <div className="space-y-1">
                                  {pTasks.sort((a, b) => {
                                    const sOrder: Record<TaskStatus, number> = { a_faire: 0, en_cours: 1, terminee: 2 };
                                    return sOrder[a.status] - sOrder[b.status];
                                  }).map(task => {
                                    const isOverdueTask = task.dueDate && task.status !== 'terminee' && new Date(task.dueDate) < new Date();
                                    return (
                                      <div
                                        key={task.id}
                                        className={`group flex items-start gap-2 p-2 rounded-lg border transition-all ${
                                          task.status === 'terminee' ? 'bg-gray-50/50 border-gray-100 opacity-50' :
                                          isOverdueTask ? 'bg-red-50/50 border-red-200' :
                                          'bg-white border-gray-200 hover:border-[#D4A03C]/30 hover:shadow-sm'
                                        }`}
                                      >
                                        <button
                                          onClick={() => toggleTaskStatus(task.id)}
                                          className="shrink-0 mt-0.5 text-gray-400 hover:text-[#D4A03C] transition-colors"
                                          title={task.status === 'terminee' ? 'Réouvrir' : task.status === 'en_cours' ? 'Terminer' : 'Commencer'}
                                        >
                                          {task.status === 'terminee' ? <CheckSquare size={15} className="text-green-500" /> :
                                           task.status === 'en_cours' ? <CheckCircle size={15} className="text-blue-500" /> :
                                           <Square size={15} />}
                                        </button>
                                        <div className="flex-1 min-w-0">
                                          <div className={`text-xs font-medium leading-tight ${task.status === 'terminee' ? 'line-through text-gray-400' : 'text-gray-800'}`}>
                                            {task.title}
                                          </div>
                                          {task.description && task.status !== 'terminee' && (
                                            <p className="text-[10px] text-gray-400 mt-0.5 leading-tight line-clamp-2">{task.description}</p>
                                          )}
                                          <div className="flex items-center gap-2 mt-1 flex-wrap">
                                            {/* Assignee — editable */}
                                            <select
                                              value={task.assignee}
                                              onChange={e => {
                                                const updated = allTasks.map(t => t.id === task.id ? { ...t, assignee: e.target.value } : t);
                                                saveTasks(updated);
                                                setAllTasks(updated);
                                              }}
                                              className="text-[10px] text-gray-500 bg-transparent border-0 p-0 pr-3 focus:outline-none cursor-pointer hover:text-[#D4A03C] appearance-none"
                                              style={{ backgroundImage: 'none' }}
                                              title="Changer le proprietaire"
                                            >
                                              {DEMO_USERS.map(u => (
                                                <option key={u.id} value={u.id}>{u.name}</option>
                                              ))}
                                            </select>
                                            {task.dueDate && (
                                              <span className={`text-[10px] flex items-center gap-0.5 ${isOverdueTask ? 'text-red-600 font-bold' : 'text-gray-400'}`}>
                                                <Clock size={9} />
                                                {task.dueDate}
                                                {isOverdueTask && ' (retard)'}
                                              </span>
                                            )}
                                            {task.autoGenerated && (
                                              <span className="text-[9px] text-[#D4A03C]/60 flex items-center gap-0.5">
                                                <Zap size={8} />auto
                                              </span>
                                            )}
                                          </div>
                                        </div>
                                        {/* Priority badge */}
                                        <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded shrink-0 ${TASK_PRIORITY_COLORS[task.priority]}`}>
                                          {task.priority === 'haute' ? 'H' : task.priority === 'moyenne' ? 'M' : 'B'}
                                        </span>
                                        {/* Delete */}
                                        <button
                                          onClick={() => {
                                            const updated = allTasks.filter(t => t.id !== task.id);
                                            saveTasks(updated);
                                            setAllTasks(updated);
                                          }}
                                          className="shrink-0 opacity-0 group-hover:opacity-100 text-gray-300 hover:text-red-500 transition-all"
                                          title="Supprimer"
                                        >
                                          <Trash2 size={12} />
                                        </button>
                                      </div>
                                    );
                                  })}
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      ) : (
                        <div className="text-center py-4">
                          {config ? (
                            <>
                              <Zap size={24} className="mx-auto mb-2 text-[#D4A03C]/40" />
                              <p className="text-xs text-gray-500">Cliquez <strong>Auto-generer</strong> pour creer les taches pour ce programme</p>
                              <p className="text-[10px] text-gray-400 mt-1">{config.tasks.length} taches — {config.estimatedTimeline}</p>
                            </>
                          ) : (
                            <p className="text-xs text-gray-400">Aucune tache</p>
                          )}
                        </div>
                      )}
                    </>
                  );
                })()}
              </section>

              {/* Ligne du temps */}
              <section>
                <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-3">
                  Historique ({selectedCase.timeline.length})
                </h3>
                {selectedCase.timeline.length === 0 ? (
                  <p className="text-xs text-gray-400">Aucun evenement</p>
                ) : (
                  <div className="space-y-3">
                    {[...selectedCase.timeline].reverse().map(ev => (
                      <div key={ev.id} className="flex gap-3">
                        <div className="flex flex-col items-center">
                          <div className="w-2 h-2 rounded-full bg-[#D4A03C] mt-1.5" />
                          <div className="w-px flex-1 bg-gray-200" />
                        </div>
                        <div className="pb-3 flex-1">
                          <div className="flex items-center gap-2 mb-0.5">
                            <span className="text-[10px] font-medium text-gray-400">{ev.date}</span>
                            <span className="text-[10px] px-1.5 py-0.5 bg-gray-100 text-gray-500 rounded">
                              {TIMELINE_TYPE_LABELS[ev.type] || ev.type}
                            </span>
                          </div>
                          <p className="text-xs text-gray-700">{ev.description}</p>
                          <p className="text-[10px] text-gray-400 mt-0.5">{getUserName(ev.userId)}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </section>
            </div>
          </div>
        </div>
      )}

      {/* Notification courriel envoyé */}
      {emailSent && (
        <div className="fixed bottom-6 right-6 z-[70] bg-green-600 text-white px-5 py-3 rounded-xl shadow-2xl flex items-center gap-3 animate-in slide-in-from-bottom">
          <CheckCircle size={18} />
          <div>
            <p className="text-sm font-medium">Courriel envoyé avec succès</p>
            <p className="text-xs text-green-200">Résultats envoyés à {emailSent}</p>
          </div>
        </div>
      )}

      {/* Modal nouveau dossier */}
      {showNewModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div className="absolute inset-0 bg-black/30" onClick={() => setShowNewModal(false)} />
          <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto mx-4">
            <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between rounded-t-2xl z-10">
              <h2 className="text-lg font-bold text-gray-900">Nouveau dossier</h2>
              <button
                onClick={() => setShowNewModal(false)}
                className="p-1 rounded-md hover:bg-gray-100 text-gray-400 hover:text-gray-600 transition-colors"
              >
                <X size={20} />
              </button>
            </div>

            <div className="px-6 py-5 space-y-4">
              {/* Validation error banner */}
              {newCaseError && (
                <div className="flex items-center gap-2 p-3 rounded-lg bg-red-50 border border-red-200 text-sm text-red-700">
                  <AlertTriangle size={16} className="shrink-0 text-red-500" />
                  <span>{newCaseError}</span>
                  <button onClick={() => setNewCaseError(null)} className="ml-auto p-0.5 rounded hover:bg-red-100">
                    <X size={14} />
                  </button>
                </div>
              )}
              {/* Client */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Client *</label>
                <select
                  value={newClientId}
                  onChange={e => { setNewClientId(e.target.value); setNewCaseError(null); }}
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#D4A03C]/30 focus:border-[#D4A03C]"
                >
                  <option value="">Selectionner un client</option>
                  {clients.map(c => (
                    <option key={c.id} value={c.id}>{c.firstName} {c.lastName} - {c.email}</option>
                  ))}
                </select>
              </div>

              {/* Programme */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Programme d&apos;immigration *</label>
                <select
                  value={newProgramId}
                  onChange={e => { setNewProgramId(e.target.value); setNewCaseError(null); }}
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#D4A03C]/30 focus:border-[#D4A03C]"
                >
                  <option value="">Selectionner un programme</option>
                  {programsByCategory.map(g => (
                    <optgroup key={g.catId} label={g.catLabel}>
                      {g.programs.map(p => (
                        <option key={p.id} value={p.id}>{p.name}</option>
                      ))}
                    </optgroup>
                  ))}
                </select>
              </div>

              {/* Localisation du client */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Localisation du client *</label>
                <div className="flex gap-3">
                  <button
                    type="button"
                    onClick={() => setNewLocation('canada')}
                    className={`flex-1 px-3 py-2 rounded-lg text-sm font-medium border transition-colors ${
                      newLocation === 'canada'
                        ? 'bg-[#EAEDF5] border-[#1B2559] text-[#1B2559]'
                        : 'border-gray-200 text-gray-500 hover:border-gray-300'
                    }`}
                  >
                    Depuis le Canada
                  </button>
                  <button
                    type="button"
                    onClick={() => setNewLocation('etranger')}
                    className={`flex-1 px-3 py-2 rounded-lg text-sm font-medium border transition-colors ${
                      newLocation === 'etranger'
                        ? 'bg-[#F7F3E8] border-[#D4A03C] text-[#D4A03C]'
                        : 'border-gray-200 text-gray-500 hover:border-gray-300'
                    }`}
                  >
                    Depuis l&apos;étranger
                  </button>
                </div>
              </div>

              {/* Titre */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Titre du dossier *</label>
                <input
                  type="text"
                  value={newTitle}
                  onChange={e => setNewTitle(e.target.value)}
                  placeholder="Ex: PEQ - Voie travailleurs"
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#D4A03C]/30 focus:border-[#D4A03C]"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                {/* Priorite */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Priorite</label>
                  <select
                    value={newPriority}
                    onChange={e => setNewPriority(e.target.value as typeof newPriority)}
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#D4A03C]/30 focus:border-[#D4A03C]"
                  >
                    {Object.entries(PRIORITY_LABELS).map(([k, v]) => (
                      <option key={k} value={k}>{v}</option>
                    ))}
                  </select>
                </div>

                {/* Echeance */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Echeance</label>
                  <input
                    type="date"
                    value={newDeadline}
                    onChange={e => setNewDeadline(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#D4A03C]/30 focus:border-[#D4A03C]"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                {/* Assigne a */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Assigne a</label>
                  <select
                    value={newAssignedTo}
                    onChange={e => setNewAssignedTo(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#D4A03C]/30 focus:border-[#D4A03C]"
                  >
                    <option value="">Selectionner</option>
                    {DEMO_USERS.map(u => (
                      <option key={u.id} value={u.id}>{u.name}</option>
                    ))}
                  </select>
                </div>

                {/* Avocat */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Avocat / Consultant</label>
                  <select
                    value={newAssignedLawyer}
                    onChange={e => setNewAssignedLawyer(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#D4A03C]/30 focus:border-[#D4A03C]"
                  >
                    <option value="">Selectionner</option>
                    {DEMO_USERS.filter(u => u.role === 'avocat_consultant' || u.role === 'coordinatrice').map(u => (
                      <option key={u.id} value={u.id}>{u.name}</option>
                    ))}
                  </select>
                </div>
              </div>

              {/* Notes */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
                <textarea
                  value={newNotes}
                  onChange={e => setNewNotes(e.target.value)}
                  rows={3}
                  placeholder="Notes sur le dossier..."
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#D4A03C]/30 focus:border-[#D4A03C] resize-none"
                />
              </div>

              {/* Info programme sélectionné + tarification */}
              {newProgramId && (() => {
                const prog = IMMIGRATION_PROGRAMS.find(p => p.id === newProgramId);
                if (!prog) return null;
                const tier = findPricingTierByProgram(newProgramId, newLocation);
                const totalPrice = tier ? tier.serviceFee + tier.governmentFee : 0;
                const totalAfterDeduction = tier ? (tier.serviceFee - FRAIS_OUVERTURE_DOSSIER) + tier.governmentFee : 0;
                return (
                  <div className="space-y-3">
                    <div className="bg-[#EAEDF5] rounded-lg p-4">
                      <h4 className="text-sm font-semibold text-[#1B2559] mb-1">{prog.name}</h4>
                      <p className="text-xs text-[#1B2559]/70 mb-2">{prog.description}</p>
                      <div className="flex items-center gap-4 text-xs text-[#1B2559]/80">
                        <span>Délai: {prog.processingTime}</span>
                      </div>
                      <p className="text-xs text-[#1B2559]/60 mt-2">
                        {prog.requiredForms.length} formulaire(s) requis seront ajoutés automatiquement
                      </p>
                    </div>

                    {tier && (
                      <div className="bg-[#F7F3E8] rounded-lg p-4 border border-[#D4A03C]/20">
                        <div className="flex items-center gap-2 mb-3">
                          <FileSignature size={16} className="text-[#D4A03C]" />
                          <h4 className="text-sm font-semibold text-[#1B2559]">Contrat de service — Généré automatiquement</h4>
                        </div>
                        <div className="grid grid-cols-2 gap-3 text-xs">
                          <div className="bg-white rounded-lg p-3">
                            <span className="text-gray-500">Honoraires professionnels</span>
                            <p className="text-lg font-bold text-[#D4A03C]">{tier.serviceFee.toLocaleString('fr-CA')} $</p>
                            <span className="text-gray-400">Après déduction: {(tier.serviceFee - FRAIS_OUVERTURE_DOSSIER).toLocaleString('fr-CA')} $</span>
                          </div>
                          <div className="bg-white rounded-lg p-3">
                            <span className="text-gray-500">Déboursés gouvernementaux</span>
                            <p className="text-lg font-bold text-gray-700">{tier.governmentFee.toLocaleString('fr-CA')} $</p>
                            <span className={`text-xs ${tier.governmentFeePayeur === 'employeur' ? 'text-orange-600 font-medium' : 'text-gray-400'}`}>
                              {tier.governmentFeePayeur === 'employeur' ? 'À la charge de l\'employeur' : 'À la charge du client'}
                            </span>
                          </div>
                        </div>
                        <div className="mt-3 flex items-start gap-2 text-xs text-[#1B2559]/70">
                          <CheckCircle2 size={14} className="text-green-600 shrink-0 mt-0.5" />
                          <span>Consultation initiale gratuite. Frais d&apos;ouverture de dossier: <strong>{FRAIS_OUVERTURE_DOSSIER} $</strong> — déduits des honoraires si le client signe le contrat. Taxes (TPS/TVQ) sur honoraires uniquement.</span>
                        </div>
                        {tier.governmentFeePayeur === 'employeur' && (
                          <div className="mt-2 flex items-start gap-2 text-xs text-orange-600">
                            <span>⚠ Les frais d&apos;EIMT ({tier.governmentFee.toLocaleString('fr-CA')} $/poste) sont à la charge exclusive de l&apos;employeur (art. 209.2 RIPR).</span>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                );
              })()}
            </div>

            {/* Boutons */}
            <div className="sticky bottom-0 bg-white border-t border-gray-200 px-6 py-4 flex items-center justify-end gap-3 rounded-b-2xl">
              <button
                onClick={() => setShowNewModal(false)}
                className="px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-800 transition-colors"
              >
                Annuler
              </button>
              <button
                onClick={saveNewCase}
                disabled={!newClientId || !newProgramId || !newTitle}
                className="px-5 py-2 bg-[#D4A03C] text-white text-sm font-medium rounded-lg hover:bg-[#B8892F] disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
              >
                Creer le dossier
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
